export interface ModelEssay {
  id: string
  subject: 'chinese' | 'english'
  abilityPoint: string
  level: number
  title: string
  content: string
  analysis: string
  techniques: string[]
  genre: string
}

export const MODEL_ESSAYS: ModelEssay[] = [
  // ═══════════════════════════════════════════════════════════════════
  // CHINESE MODEL ESSAYS
  // ═══════════════════════════════════════════════════════════════════

  // ── L3 开头段 ──────────────────────────────────────────────────────
  {
    id: 'cn-l3-001',
    subject: 'chinese',
    abilityPoint: '开头段',
    level: 3,
    title: '议论文开头 - 引用名言式',
    content: '司马迁曾言："人固有一死，或重于泰山，或轻于鸿毛。"真正的勇气，不在于赴死的决绝，而在于面对困境时依然选择前行的坚定。在当今社会，勇气的内涵早已超越了生死的抉择，它体现在每一个普通人面对挑战时的抉择之中。',
    analysis: '以名言引入，迅速建立文化底蕴；用"不在于...而在于..."的对比结构引出核心论点；最后一句将历史与当下连接，拓展了论述空间。',
    techniques: ['名言引入', '对比结构', '古今连接'],
    genre: '议论文',
  },
  {
    id: 'cn-l3-002',
    subject: 'chinese',
    abilityPoint: '开头段',
    level: 3,
    title: '议论文开头 - 设问引入式',
    content: '什么是真正的勇气？是战场上的冲锋陷阵？是面对不公时的挺身而出？或许都是，但又不全是。真正的勇气，是一种在理性判断后的坚持，是在众人皆退时依然前行的笃定。',
    analysis: '用设问引发思考，连续追问制造悬念；"或许都是，但又不全是"形成转折，引出独特立意。',
    techniques: ['设问引入', '悬念制造', '转折引出论点'],
    genre: '议论文',
  },
  {
    id: 'cn-l3-003',
    subject: 'chinese',
    abilityPoint: '开头段',
    level: 3,
    title: '议论文开头 - 排比引入式',
    content: '勇气是屈原"亦余心之所善兮，虽九死其犹未悔"的执着；勇气是文天祥"人生自古谁无死，留取丹心照汗青"的壮烈；勇气是林则徐"苟利国家生死以，岂因祸福避趋之"的担当。古往今来，勇气从来不是空洞的口号，而是以行动书写的生命答卷。',
    analysis: '三个排比句以"勇气是..."贯穿，引用不同朝代的名句，形成时间跨度和文化厚度；最后一句总结升华，从具体事例中提炼出"行动"这一核心关键词。',
    techniques: ['排比引入', '古诗引用', '从具体到抽象'],
    genre: '议论文',
  },
  {
    id: 'cn-l3-004',
    subject: 'chinese',
    abilityPoint: '开头段',
    level: 3,
    title: '议论文开头 - 对比引入式',
    content: '面对同样的困境，有人选择退缩，有人选择前行；面对同样的压力，有人选择妥协，有人选择坚守。人生的分野，往往就在这一念之间。勇气，正是那个让我们在犹豫中做出正确选择的力量。',
    analysis: '两组对比句式形成鲜明对照，揭示"选择"的差异；"一念之间"制造紧迫感；最后一句点明论点，将勇气定义为"做出正确选择的力量"。',
    techniques: ['对比引入', '选择对照', '聚焦核心概念'],
    genre: '议论文',
  },
  {
    id: 'cn-l3-005',
    subject: 'chinese',
    abilityPoint: '开头段',
    level: 3,
    title: '议论文开头 - 故事引入式',
    content: '公元前681年，齐桓公面对管仲的箭伤，选择了宽容与信任。这一箭之仇，本可让他置管仲于死地，但他看到了治国之才，放下了个人恩怨。正是这一念之间的勇气，成就了齐国的霸业，也让我们看到了勇气的另一面——它不是冲动，而是超越自我的智慧。',
    analysis: '以具体历史故事开篇，生动可感；"一箭之仇"的细节增加叙事张力；从故事中自然引出"勇气不是冲动而是智慧"的独特论点，立意深刻。',
    techniques: ['故事引入', '细节描写', '从故事中提炼观点'],
    genre: '议论文',
  },

  // ── L4 论证段 ──────────────────────────────────────────────────────
  {
    id: 'cn-l4-001',
    subject: 'chinese',
    abilityPoint: '论证段',
    level: 4,
    title: '论证段 - 事例论证',
    content: '历史证明，勇于创新是推动文明进步的关键。商鞅变法，以"徙木立信"打破旧制束缚，激发了秦国的社会活力。他深知改革之难，却选择以实际行动证明变法的决心。正是这种敢于突破常规的勇气，铸就了秦国的强盛，也为后来的统一奠定了基础。可见，真正的创新不仅需要智慧，更需要直面阻力的勇气。',
    analysis: '论点明确→典型事例→深入分析→回扣论点，形成完整论证闭环。事例选择精准，分析深入到"敢于突破常规"的精神层面。',
    techniques: ['事例论证', '论证闭环', '精神层面分析'],
    genre: '议论文',
  },
  {
    id: 'cn-l4-002',
    subject: 'chinese',
    abilityPoint: '论证段',
    level: 4,
    title: '论证段 - 因果分析论证',
    content: '教育的本质在于唤醒而非灌输。当课堂变成知识的单向传输，学生便失去了思考的主动性。填鸭式教育看似高效，实则扼杀了好奇心与创造力——学生记住了公式，却不会提出问题；背熟了范文，却写不出自己的文字。反之，启发式教育通过问题引导和情境创设，让学生在探索中建构知识体系，这才是教育应有的样子。因此，教育改革的关键在于转变观念：从"教什么"转向"怎么教"，从"让学生记住"转向"让学生思考"。',
    analysis: '先立论点→正反对比分析因果→最终得出改革方向。因果链条清晰：灌输→被动→丧失创造力；启发→主动→建构知识。逻辑严密，层层递进。',
    techniques: ['因果分析', '正反对比', '层层递进'],
    genre: '议论文',
  },
  {
    id: 'cn-l4-003',
    subject: 'chinese',
    abilityPoint: '论证段',
    level: 4,
    title: '论证段 - 对比论证',
    content: '传承与创新，从来不是非此即彼的选择。故宫文创将古老的文物赋予了现代的生命力：一支口红，印着千里江山的青绿；一本日历，藏着三百六十五件国宝。它没有抛弃传统，而是用创新的语言重新讲述传统的故事。反观某些"国潮"品牌，简单地将龙凤图案贴在商品上，却毫无文化内涵，最终沦为廉价的噱头。两相对比可见，真正的传承不是照搬，而是在深刻理解基础上的创造性转化。',
    analysis: '正面案例（故宫文创）+反面案例（廉价国潮）形成鲜明对比；分析深入到"创造性转化"的高度；结论精炼有力。',
    techniques: ['对比论证', '正反案例', '从现象到本质'],
    genre: '议论文',
  },
  {
    id: 'cn-l4-004',
    subject: 'chinese',
    abilityPoint: '论证段',
    level: 4,
    title: '论证段 - 比喻论证',
    content: '成长如同一棵树的年轮。每一次挫折，都是一道深深的刻痕；每一次突破，都是一圈坚实的扩展。没有哪棵树能跳过年轮直接长高，也没有哪个人能绕过困难直接成熟。那些看似阻碍我们成长的风雨，恰恰是在为我们扎根、为未来蓄力。正如一棵经历风霜的古树，远比温室中的幼苗更加挺拔。因此，不必惧怕成长中的阵痛，那是生命在为更高的飞翔做准备。',
    analysis: '以"年轮"为喻贯穿全段，从树的成长类比人的成长；比喻层层递进（刻痕→扩展→扎根→蓄力）；最后落脚到"不惧阵痛"的论点。',
    techniques: ['比喻论证', '类比推理', '层层递进的比喻'],
    genre: '议论文',
  },
  {
    id: 'cn-l4-005',
    subject: 'chinese',
    abilityPoint: '论证段',
    level: 4,
    title: '论证段 - 引用论证',
    content: '"纸上得来终觉浅，绝知此事要躬行。"陆游的诗句道出了实践的重要性。知识若不付诸行动，便只是书本上的铅字；理论若不经过检验，便只是空中的楼阁。屠呦呦从古籍中获得灵感，经过数百次实验，才提取出青蒿素；袁隆平在稻田中反复摸索，才培育出杂交水稻。他们的成功告诉我们：唯有将知识与实践相结合，才能创造出真正的价值。',
    analysis: '以诗句引出论点→名言阐释→事例佐证→总结升华。引用论证与事例论证相结合，论据典型有力。',
    techniques: ['引用论证', '名言+事例结合', '从理论到实践'],
    genre: '议论文',
  },

  // ── L5 过渡段 ──────────────────────────────────────────────────────
  {
    id: 'cn-l5-001',
    subject: 'chinese',
    abilityPoint: '过渡段',
    level: 5,
    title: '过渡段 - 承上启下式',
    content: '如果说勇气是面对困境时的坚守，那么智慧就是做出正确选择的能力。勇气与智慧，从来都是相辅相成的。没有勇气，智慧便无从施展；没有智慧，勇气便可能沦为鲁莽。唯有将二者结合，才能在人生的十字路口做出正确的抉择。',
    analysis: '用"如果说...那么..."的句式自然承接上文关于勇气的论述，同时引出下文关于智慧的讨论；中间用"相辅相成"点明关系；最后用条件句过渡到更深的论述。',
    techniques: ['承上启下', '假设关系', '点明逻辑关系'],
    genre: '议论文',
  },
  {
    id: 'cn-l5-002',
    subject: 'chinese',
    abilityPoint: '过渡段',
    level: 5,
    title: '过渡段 - 递进过渡',
    content: '个人的勇气固然可贵，但当千千万万个普通人汇聚起勇气的力量，便能推动整个社会的进步。从个体到群体，从微观到宏观，勇气的价值在放大中得到了更充分的彰显。',
    analysis: '以"固然...但..."的让步关系承接上文的个人层面，用"从个体到群体"的递进引出社会层面的论述；句式简洁有力。',
    techniques: ['递进过渡', '让步转折', '视角转换'],
    genre: '议论文',
  },
  {
    id: 'cn-l5-003',
    subject: 'chinese',
    abilityPoint: '过渡段',
    level: 5,
    title: '过渡段 - 转折过渡',
    content: '然而，勇气并不意味着盲目冒进。真正的勇气，是经过深思熟虑后的果断行动，是在充分评估风险后依然选择前行的坚定。因此，我们更需要理性来为勇气导航。',
    analysis: '用"然而"自然转折，从"勇气"过渡到"理性"的论述；先破后立，先指出误区再给出正确定义；最后一句为下文张本。',
    techniques: ['转折过渡', '先破后立', '概念辨析'],
    genre: '议论文',
  },

  // ── L6 结尾段 ──────────────────────────────────────────────────────
  {
    id: 'cn-l6-001',
    subject: 'chinese',
    abilityPoint: '结尾段',
    level: 6,
    title: '结尾段 - 升华式',
    content: '勇气从来不是鲁莽者的专利，而是理性者的坚守。在这个充满不确定性的时代，我们每个人都需要勇气——不是去改变世界，而是在认清生活的真相后，依然热爱生活。愿我们都能在平凡的日子里，做一个有勇气的普通人。',
    analysis: '跳出个人层面，上升到时代高度；引用罗曼·罗兰的名句进行升华；最后落脚到"普通人"，拉近距离，引发共鸣。',
    techniques: ['时代升华', '名句化用', '回归平凡'],
    genre: '议论文',
  },
  {
    id: 'cn-l6-002',
    subject: 'chinese',
    abilityPoint: '结尾段',
    level: 6,
    title: '结尾段 - 呼应开头式',
    content: '回望历史，商鞅以勇气破旧立新；审视当下，无数普通人以勇气守护日常。勇气的形式在变，但其内核始终未变——那就是在认清现实之后，依然选择相信与坚持。这，便是勇气给予我们最深刻的启示。',
    analysis: '以"回望...审视..."呼应前文的历史事例和现实论述；最后以"最深刻的启示"收束全文，余味悠长。',
    techniques: ['首尾呼应', '古今照应', '总结升华'],
    genre: '议论文',
  },
  {
    id: 'cn-l6-003',
    subject: 'chinese',
    abilityPoint: '结尾段',
    level: 6,
    title: '结尾段 - 号召式',
    content: '让我们以勇气为帆，以智慧为舵，在时代的浪潮中破浪前行。不必等待完美的时机，因为勇气本身就是最好的时机。从此刻开始，做一个有勇气的人，做一件有勇气的事，让勇气成为我们生命中最亮的底色。',
    analysis: '用比喻（帆与舵）增加文采；"不必等待...因为..."打破等待心理；最后三个"做"字形成排比，号召力强。',
    techniques: ['比喻升华', '排比号召', '从现在开始'],
    genre: '议论文',
  },
  {
    id: 'cn-l6-004',
    subject: 'chinese',
    abilityPoint: '结尾段',
    level: 6,
    title: '结尾段 - 余韵式',
    content: '也许勇气并不总轰轰烈烈，它可能只是深夜台灯下的一次次修改，是面对质疑时的沉默坚持，是跌倒后拍拍尘土的重新出发。这些看似平凡的瞬间，恰是勇气最真实的模样。',
    analysis: '以"也许"开头，留有余地；三个"是..."的排比句勾勒出日常中的勇气画面；最后点题，言有尽而意无穷。',
    techniques: ['留白余韵', '日常化视角', '排比勾勒'],
    genre: '议论文',
  },

  // ── L7 全文整合 ────────────────────────────────────────────────────
  {
    id: 'cn-l7-001',
    subject: 'chinese',
    abilityPoint: '全文',
    level: 7,
    title: '完整议论文 - 勇气的三重境界',
    content: '勇气是什么？是面对困难时的不退缩？是做出选择时的果断？或许都是，但又不全是。在我看来，勇气有三重境界：一曰敢于面对，二曰敢于选择，三曰敢于承担。\n\n第一重境界，是敢于面对现实的勇气。司马迁遭受宫刑之辱，却没有选择以死逃避，而是忍辱负重，完成了"史家之绝唱"。他在《报任安书》中写道："人固有一死，或重于泰山，或轻于鸿毛。"正是这种直面惨淡人生的勇气，让他超越了个人的苦难，为后世留下了不朽的著作。面对，是勇气的起点。\n\n第二重境界，是敢于做出选择的勇气。陶渊明在"误落尘网中"之后，终于"觉今是而昨非"，选择了"采菊东篱下"的归隐之路。在那个追逐功名的时代，他的选择无疑需要巨大的勇气。更可贵的是，他不是逃避，而是遵从内心的选择。选择，是勇气的升华。\n\n第三重境界，是敢于承担后果的勇气。林则徐虎门销烟，明知会招致列强的报复，却依然选择了维护民族尊严。"苟利国家生死以，岂因祸福避趋之"，这句诗是他勇于担当的最好注脚。承担，是勇气的最高境界。\n\n三重境界，层层递进。面对是基础，选择是关键，承担是归宿。在当今社会，我们或许不需要面对生死的考验，但生活中的每一次抉择、每一次担当，都是对勇气的诠释。愿我们都能修炼出属于自己的勇气，在平凡的生活中活出不平凡的精彩。',
    analysis: '采用"三重境界"的递进式结构，逻辑严密；每重境界都有典型事例和诗句支撑，论据充实；从历史到当下，视野开阔；首尾呼应，结构完整。',
    techniques: ['递进式结构', '分论点展开', '事例论证', '首尾呼应'],
    genre: '议论文',
  },
  {
    id: 'cn-l7-002',
    subject: 'chinese',
    abilityPoint: '全文',
    level: 7,
    title: '完整议论文 - 传承与创新',
    content: '故宫的红墙黄瓦下，文创产品琳琅满目；敦煌的壁画前，数字技术让千年艺术重焕生机。传承与创新，这对看似矛盾的概念，正在当代中国上演着最精彩的对话。\n\n传承是根，创新是叶。没有根的滋养，叶终将枯萎；没有叶的光合，根也难以存活。传统文化的传承不是将文物锁在博物馆的玻璃柜中，而是让它活在人们的日常生活里。故宫文创的成功正在于此：一支口红，印着千里江山的青绿；一本日历，藏着三百六十五件国宝。它没有抛弃传统，而是用创新的语言重新讲述传统的故事。\n\n然而，创新必须建立在深刻理解传统的基础上。某些"国潮"品牌简单地将龙凤图案贴在商品上，却毫无文化内涵，最终沦为廉价的噱头。这种"创新"不是传承，而是对传统的消费。真正的创新，是先读懂传统的"魂"，再赋予它新的"形"。\n\n更进一步说，传承与创新的最终目的是服务于人。无论是传统技艺的保护，还是新技术的应用，都应该让人更好地感受文化之美、生活之美。当年轻人穿着汉服走在街头，当老人在手机上欣赏京剧，传承与创新便找到了最好的交汇点。\n\n站在新时代的起点上，我们既要守住文化的根脉，也要拥抱时代的浪潮。唯有在传承中创新，在创新中传承，中华文化才能生生不息，历久弥新。',
    analysis: '以现象引入→提出核心观点→正反论证→深化分析→总结展望，层层递进；正反案例对比鲜明；分析深入到"形"与"魂"的辩证关系；语言流畅，逻辑清晰。',
    techniques: ['递进式结构', '正反对比论证', '辩证分析', '时代视野'],
    genre: '议论文',
  },

  // ═══════════════════════════════════════════════════════════════════
  // ENGLISH MODEL ESSAYS
  // ═══════════════════════════════════════════════════════════════════

  // ── L1 句式仿写 ───────────────────────────────────────────────────
  {
    id: 'en-l1-001',
    subject: 'english',
    abilityPoint: '句式',
    level: 1,
    title: '倒装句',
    content: 'Only by facing our fears can we truly grow as individuals. Not only did the reform bring economic prosperity, but it also transformed the social landscape. Never have we witnessed such a rapid technological advancement in human history.',
    analysis: '三个倒装句分别展示不同类型的倒装：Only+状语倒装、Not only...but also倒装、Never+完成时倒装。句式多样，表达有力。',
    techniques: ['Only倒装', 'Not only倒装', 'Never倒装'],
    genre: '议论文',
  },
  {
    id: 'en-l1-002',
    subject: 'english',
    abilityPoint: '句式',
    level: 1,
    title: '强调句',
    content: 'It is through adversity that we discover our true strength. It was the dedication of frontline workers that made the fight against the pandemic possible. It is not the critic who counts, but the person in the arena who strives valiantly.',
    analysis: '三个强调句分别强调不同成分：强调方式状语、强调主语、强调主语（含对比）。It is/was...that/who结构运用纯熟，表达效果突出。',
    techniques: ['It is...that强调', 'It was...that强调', 'It is...who强调'],
    genre: '议论文',
  },
  {
    id: 'en-l1-003',
    subject: 'english',
    abilityPoint: '句式',
    level: 1,
    title: '分词结构',
    content: 'Inspired by the success of renewable energy projects, many countries have committed to reducing carbon emissions. Having witnessed the devastating effects of climate change, young people around the world are demanding urgent action. Given the rapid pace of technological change, adapting to new skills has become essential for career development.',
    analysis: '三个分词结构分别展示过去分词作状语、现在分词完成式作状语、过去分词+介词结构。分词短语使句子紧凑高效，表达正式。',
    techniques: ['过去分词状语', '分词完成式', '分词+介词结构'],
    genre: '议论文',
  },
  {
    id: 'en-l1-004',
    subject: 'english',
    abilityPoint: '句式',
    level: 1,
    title: '虚拟语气',
    content: 'If I were in charge of education reform, I would prioritize critical thinking over memorization. Had the government invested more in renewable energy earlier, the environmental crisis might not be so severe. It is essential that every student be given the opportunity to develop their full potential.',
    analysis: '三个虚拟语气句分别展示：与现在事实相反的虚拟、与过去事实相反的虚拟（省略if倒装）、suggest/order类虚拟。覆盖了高考常考的虚拟语气类型。',
    techniques: ['与现在相反虚拟', '与过去相反虚拟', 'suggest类虚拟'],
    genre: '议论文',
  },

  // ── L2 段落骨架 PEEL ──────────────────────────────────────────────
  {
    id: 'en-l2-001',
    subject: 'english',
    abilityPoint: '段落',
    level: 2,
    title: 'PEEL段落 - 健康话题',
    content: 'Regular exercise is essential for maintaining good mental health (Point). A study conducted by Harvard Medical School found that individuals who exercise for at least 30 minutes a day report 43% fewer days of poor mental health (Evidence). This is because physical activity stimulates the release of endorphins, which are natural mood lifters, and also reduces levels of stress hormones such as cortisol (Explanation). Therefore, incorporating a daily exercise routine can be a powerful strategy for improving psychological well-being (Link).',
    analysis: '完整的PEEL结构：主题句明确→权威数据支撑→科学原理解释→自然过渡总结。各部分衔接流畅，逻辑清晰。',
    techniques: ['PEEL结构', '权威引用', '因果分析'],
    genre: '议论文',
  },
  {
    id: 'en-l2-002',
    subject: 'english',
    abilityPoint: '段落',
    level: 2,
    title: 'PEEL段落 - 教育话题',
    content: 'Project-based learning significantly enhances student engagement and knowledge retention (Point). Research from Stanford University shows that students who participate in project-based curricula score 20% higher on assessments than those in traditional classrooms (Evidence). This is because hands-on projects require students to apply theoretical knowledge to real-world problems, thereby deepening their understanding and making learning more meaningful (Explanation). As a result, educators are increasingly adopting project-based approaches to create more dynamic and effective learning environments (Link).',
    analysis: '标准PEEL结构：明确的观点→斯坦福大学研究数据→解释"应用→理解"的机制→展望教育趋势。Evidence部分引用权威机构，增强说服力。',
    techniques: ['PEEL结构', '学术引用', '机制解释'],
    genre: '议论文',
  },
  {
    id: 'en-l2-003',
    subject: 'english',
    abilityPoint: '段落',
    level: 2,
    title: 'PEEL段落 - 环境话题',
    content: 'Single-use plastics pose a severe threat to marine ecosystems (Point). According to the United Nations Environment Programme, approximately 8 million tons of plastic waste enter the ocean each year, causing the death of over 100,000 marine animals annually (Evidence). The reason is that plastics do not biodegrade but instead break down into microplastics, which are ingested by fish and other organisms, entering the food chain and ultimately affecting human health as well (Explanation). This alarming reality underscores the urgent need for comprehensive policies to reduce plastic consumption and promote sustainable alternatives (Link).',
    analysis: 'PEEL结构完整：海洋生态威胁→联合国数据→微塑料机制解释→政策呼吁。Explanation部分从塑料分解到食物链到人类健康，逻辑链条清晰。',
    techniques: ['PEEL结构', '权威数据', '逻辑链条'],
    genre: '议论文',
  },
  {
    id: 'en-l2-004',
    subject: 'english',
    abilityPoint: '段落',
    level: 2,
    title: 'PEEL段落 - 科技话题',
    content: 'Artificial intelligence has the potential to revolutionize healthcare diagnostics (Point). A recent study published in Nature Medicine demonstrated that AI algorithms can detect certain cancers with accuracy rates exceeding 94%, outperforming experienced radiologists in specific scenarios (Evidence). This remarkable capability stems from AI\'s ability to analyze vast datasets of medical images, identifying subtle patterns that may escape even the most trained human eye (Explanation). Consequently, integrating AI into clinical practice could lead to earlier detection, more personalized treatment plans, and ultimately, improved patient outcomes (Link).',
    analysis: 'PEEL结构严谨：AI医疗潜力→Nature Medicine研究→AI图像分析能力→临床应用展望。Evidence引用顶刊研究，Explanation从技术原理角度解释，Link展望实际应用。',
    techniques: ['PEEL结构', '顶刊引用', '技术原理解释'],
    genre: '议论文',
  },

  // ── L3 应用文格式 ──────────────────────────────────────────────────
  {
    id: 'en-l3-001',
    subject: 'english',
    abilityPoint: '应用文',
    level: 3,
    title: '建议信 - 校园环保',
    content: 'Dear Sir or Madam,\n\nI am writing to offer some suggestions regarding the environmental initiatives at our school. Having observed the current situation, I believe there are several measures that could significantly improve our campus sustainability.\n\nFirstly, I suggest that the school introduce a comprehensive recycling program, placing clearly labeled bins in every building for paper, plastic, and organic waste. Secondly, it would be beneficial to organize monthly environmental awareness campaigns, such as tree-planting days or clean-up drives, to engage students in hands-on activities. Lastly, the cafeteria could reduce food waste by implementing a "take what you need" policy and donating surplus meals to local charities.\n\nI am confident that these measures will not only reduce our environmental footprint but also foster a sense of responsibility among students. I would be delighted to help implement any of these suggestions.\n\nYours sincerely,\nLi Hua',
    analysis: '格式完整：称呼→自我介绍→建议（Firstly/Secondly/Lastly分点）→展望→落款。建议具体可操作，语言正式得体。',
    techniques: ['建议信格式', '分点建议', '正式语体'],
    genre: '应用文',
  },
  {
    id: 'en-l3-002',
    subject: 'english',
    abilityPoint: '应用文',
    level: 3,
    title: '邀请信 - 文化交流活动',
    content: 'Dear Professor Johnson,\n\nI am delighted to invite you to attend our school\'s Annual Cultural Exchange Festival, which will be held on June 15th in the school auditorium. As a distinguished scholar in cross-cultural communication, your presence would be a great honor for our students and faculty.\n\nThe festival will feature a variety of activities, including traditional music performances, calligraphy demonstrations, and a panel discussion on cultural diversity. We would be particularly grateful if you could deliver a brief speech on the importance of intercultural understanding, sharing your insights from your extensive research.\n\nThe event will commence at 2:00 PM and is expected to conclude by 5:00 PM. Please let us know at your earliest convenience whether you are able to attend, so that we may make the necessary arrangements.\n\nWe sincerely hope you will join us for this memorable occasion.\n\nYours sincerely,\nLi Hua',
    analysis: '邀请信格式规范：自我介绍→活动介绍→具体邀请（演讲）→时间地点→礼貌收尾。语气热情而不失正式，邀请理由充分。',
    techniques: ['邀请信格式', '具体细节', '礼貌得体'],
    genre: '应用文',
  },
  {
    id: 'en-l3-003',
    subject: 'english',
    abilityPoint: '应用文',
    level: 3,
    title: '演讲稿 - 阅读的力量',
    content: 'Good morning, everyone!\n\nIt is a great privilege to stand before you today to share my thoughts on the power of reading. In an age dominated by screens and social media, the habit of reading may seem old-fashioned, but I firmly believe it remains one of the most valuable gifts we can give ourselves.\n\nReading opens doors to worlds we have never visited, introduces us to minds we have never met, and challenges us to think in ways we never have. A single book can transport us across centuries, bridge cultural divides, and inspire us to become better versions of ourselves.\n\nConsider this: the most successful leaders, innovators, and thinkers throughout history have been avid readers. From Lincoln to Musk, from Confucius to Hawking, the habit of reading has been a common thread in their journeys.\n\nSo let us pick up a book today. Let us rediscover the joy of turning pages, the thrill of getting lost in a story, and the satisfaction of gaining new knowledge. Remember, a reader lives a thousand lives before he dies. The man who never reads lives only one.\n\nThank you!',
    analysis: '演讲稿格式正确：问候→开篇点题→论证（排比+事例）→号召→结尾。语言富有感染力，多用we/us拉近距离，引用George R.R. Martin名句增强说服力。',
    techniques: ['演讲稿格式', '排比增强气势', '引用名句', '互动式语言'],
    genre: '应用文',
  },

  // ── L4 读后续写 ────────────────────────────────────────────────────
  {
    id: 'en-l4-001',
    subject: 'english',
    abilityPoint: '续写开头',
    level: 4,
    title: '读后续写 - 悬念式开头',
    content: 'My heart was pounding so hard I could hear it in my ears. The old wooden door creaked open, revealing nothing but darkness beyond. I hesitated for only a moment before stepping forward, my flashlight cutting a thin beam through the shadows. The air was thick with the scent of dust and something else — something I couldn\'t quite identify. As my eyes adjusted, I noticed something glinting on the floor ahead, and I realized that whatever secret this place held, it was about to be revealed.',
    analysis: '衔接前文的探险场景，保持紧张氛围；通过感官描写（心跳声、木门嘎吱声、灰尘气味）营造悬念；"glinting on the floor"设置新的悬念点，为后续情节铺垫。',
    techniques: ['感官描写', '悬念设置', '环境烘托'],
    genre: '记叙文',
  },
  {
    id: 'en-l4-002',
    subject: 'english',
    abilityPoint: '续写开头',
    level: 4,
    title: '读后续写 - 情感式开头',
    content: 'Tears blurred my vision as I watched the train pull away from the platform. My grandmother stood at the window, her wrinkled hand pressed against the glass, her lips forming words I could no longer hear. The platform was emptying now, but I remained rooted to the spot, replaying in my mind every moment we had shared that afternoon. Her laughter, her stories, the way she had tucked a small envelope into my pocket with a knowing smile — all of it rushed back in a wave of emotion that I was powerless to resist.',
    analysis: '衔接离别场景，情感真挚；通过细节（奶奶贴在玻璃上的手、口袋里的信封）承接前文并暗示后续发展；"small envelope"为下文埋下伏笔。',
    techniques: ['情感渲染', '细节伏笔', '内心独白'],
    genre: '记叙文',
  },

  // ── L5 语法纠错 ────────────────────────────────────────────────────
  {
    id: 'en-l5-001',
    subject: 'english',
    abilityPoint: '语法纠错',
    level: 5,
    title: '常见语法错误 - 主谓一致与冠词',
    content: '【错误示范】The number of students who has passed the exam are increasing year by year. Each of the participants have to submit their reports before Friday. Education is the one of the most important investment a society can make.\n\n【改正】The number of students who have passed the exam is increasing year by year. Each of the participants has to submit his or her report before Friday. Education is one of the most important investments a society can make.\n\n【解析】①"The number of"作主语时谓语用单数，who引导的定语从句先行词是students，从句谓语用复数；②Each作主语时谓语用单数，each是单数代词，his or her与之保持一致；③one of the + 复数名词，去掉the。',
    analysis: '覆盖了高考常考的三类语法错误：主谓一致（The number of / The number of...who）、代词一致（each...his or her）、冠词误用（one of the + 复数）。错误典型，解析清晰。',
    techniques: ['主谓一致', '代词一致', '冠词用法'],
    genre: '议论文',
  },
  {
    id: 'en-l5-002',
    subject: 'english',
    abilityPoint: '语法纠错',
    level: 5,
    title: '常见语法错误 - 时态与非谓语',
    content: '【错误示范】If I was you, I would accept the offer without hesitation. Having finished his homework, the TV was turned on by Tom. Not until the teacher came into the classroom the students stopped talking.\n\n【改正】If I were you, I would accept the offer without hesitation. Having finished his homework, Tom turned on the TV. Not until the teacher came into the classroom did the students stop talking.\n\n【解析】①虚拟语气中be动词一律用were；②分词短语作状语时，其逻辑主语必须与句子主语一致（Tom是finishing和turning on两个动作的执行者）；③Not until置于句首时，主句需部分倒装。',
    analysis: '覆盖三类高频错误：虚拟语气的be动词形式、分词作状语的逻辑主语、not until的倒装。每处错误都附有详细解析，便于学生理解和记忆。',
    techniques: ['虚拟语气', '分词逻辑主语', '部分倒装'],
    genre: '议论文',
  },

  // ── L6 全文写作 ────────────────────────────────────────────────────
  {
    id: 'en-l6-001',
    subject: 'english',
    abilityPoint: '全文',
    level: 6,
    title: '完整议论文 - The Value of Volunteering',
    content: 'In today\'s fast-paced world, where academic achievement and career success often dominate our priorities, the value of volunteering is frequently overlooked. However, I firmly believe that volunteering is not merely a selfless act of kindness but a transformative experience that benefits both the individual and society as a whole.\n\nTo begin with, volunteering provides invaluable opportunities for personal growth. When we step out of our comfort zones to help others, we develop empathy, communication skills, and a broader perspective on life. For instance, a student who volunteers at a local nursing home not only brings joy to elderly residents but also gains a deeper appreciation for the wisdom and experiences of older generations. Such experiences shape our character in ways that no textbook can.\n\nFurthermore, volunteering strengthens the fabric of our communities. In an era of increasing social isolation, volunteer initiatives bring people together across age, class, and cultural boundaries. Community gardens, food banks, and mentoring programs create connections that foster mutual understanding and solidarity. These bonds are the foundation of a healthy, resilient society.\n\nAdmittedly, some may argue that volunteering takes time away from more productive pursuits. Yet this view is shortsighted, as the skills and perspectives gained through volunteering often enhance one\'s effectiveness in other areas of life. Moreover, the satisfaction of contributing to something larger than oneself is a reward that no material gain can match.\n\nIn conclusion, volunteering enriches our lives in profound ways. It cultivates our humanity, strengthens our communities, and gives us a sense of purpose that transcends individual ambition. As the saying goes, "The best way to find yourself is to lose yourself in the service of others." Let us embrace volunteering, not as an obligation, but as a privilege.',
    analysis: '结构完整：引入→分论点1（个人成长）→分论点2（社区建设）→让步反驳→总结升华。语言地道，句式多样（倒装、分词、非限制性定语从句），论证充分。',
    techniques: ['完整议论文结构', '分论点展开', '让步反驳', '多样句式'],
    genre: '议论文',
  },
  {
    id: 'en-l6-002',
    subject: 'english',
    abilityPoint: '全文',
    level: 6,
    title: '完整议论文 - Digital Literacy in the Modern Age',
    content: 'The digital revolution has transformed every aspect of our lives, from how we communicate to how we learn and work. Yet amidst this rapid technological change, a critical skill set has emerged that is becoming as fundamental as reading and writing: digital literacy. I believe that digital literacy should be a core component of modern education, as it equips students with the tools necessary to navigate an increasingly complex world.\n\nFirst and foremost, digital literacy empowers individuals to access and evaluate information effectively. In an age of misinformation and "fake news," the ability to discern credible sources from unreliable ones is essential. Students who are digitally literate can critically assess the information they encounter online, making informed decisions rather than falling prey to manipulation. This skill is not merely academic — it is vital for responsible citizenship.\n\nMoreover, digital literacy opens doors to opportunities that were previously inaccessible. From online courses and remote work to digital entrepreneurship, technology has democratized access to education and employment. Students in rural areas can now learn from world-class instructors through video lectures, and aspiring entrepreneurs can launch businesses with minimal capital using digital platforms. Without digital literacy, however, these opportunities remain out of reach.\n\nCritics may argue that an overemphasis on technology in education could diminish the importance of traditional skills and face-to-face interaction. While this concern is valid, digital literacy does not replace these skills — it complements them. A digitally literate student is not one who stares at a screen all day, but one who uses technology thoughtfully and purposefully to enhance their learning and communication.\n\nIn conclusion, digital literacy is no longer optional — it is a necessity. By integrating digital skills into the curriculum, we prepare students not just for exams, but for life in the 21st century. As the world continues to evolve, our education system must evolve with it, ensuring that every student has the tools to thrive in the digital age.',
    analysis: '结构清晰：引入→分论点1（信息评估）→分论点2（机会平等）→让步反驳→总结展望。多处使用高级句式（倒装、分词、非限制性定语从句、强调句），论证有深度。',
    techniques: ['完整议论文结构', '让步反驳', '高级句式', '时代视野'],
    genre: '议论文',
  },
]

export function getModelEssays(
  subject: 'chinese' | 'english',
  level: number,
  abilityPoint?: string,
): ModelEssay[] {
  return MODEL_ESSAYS.filter(
    (e) =>
      e.subject === subject &&
      e.level === level &&
      (abilityPoint ? e.abilityPoint === abilityPoint : true),
  )
}
