import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Clean existing data
  await prisma.material.deleteMany()
  await prisma.abilityProfile.deleteMany()
  await prisma.trainingRecord.deleteMany()
  await prisma.assessment.deleteMany()
  await prisma.topic.deleteMany()
  await prisma.user.deleteMany()

  // ========== Chinese Topics (议论文) ==========
  const chineseArgumentativeTopics = [
    {
      id: 'cn-arg-001',
      source: '高考真题',
      year: 2024,
      region: '全国甲卷',
      subject: 'chinese',
      type: '议论文',
      title: '关于\"移动支付\"的思考',
      description: '随着移动支付的普及，人们的生活方式发生了巨大变化。请以\"移动支付与生活\"为主题，写一篇议论文。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['科技', '生活', '移动支付']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-002',
      source: '高考真题',
      year: 2023,
      region: '全国乙卷',
      subject: 'chinese',
      type: '议论文',
      title: '故事的力量',
      description: '好的故事，可以帮我们更好地表达和沟通，可以触动心灵、启迪智慧；好的故事，可以改变一个人的形象，可以展现民族的形象...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['故事', '表达', '文化']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-003',
      source: '高考真题',
      year: 2023,
      region: '新课标I卷',
      subject: 'chinese',
      type: '议论文',
      title: '故事的力量',
      description: '好的故事，可以帮我们更好地表达和沟通，可以触动心灵、启迪智慧；好的故事，可以改变一个人的形象，可以展现民族的形象。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['故事', '沟通', '智慧']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-004',
      source: '高考真题',
      year: 2022,
      region: '全国甲卷',
      subject: 'chinese',
      type: '议论文',
      title: '可为与有为',
      description: '中国共产主义青年团成立100周年之际，中央广播电视总台推出微纪录片，介绍一群在不同行业奋发有为的青年...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['青年', '奋斗', '理想']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-005',
      source: '高考真题',
      year: 2022,
      region: '新高考I卷',
      subject: 'chinese',
      type: '议论文',
      title: '本手、妙手、俗手',
      description: '围棋中有\"本手、妙手、俗手\"之说。本手是合乎棋理的正规下法；妙手是出人意料的精妙下法；俗手是貌似合理而从全局看通常会受损的下法。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['围棋', '基础', '创新']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-006',
      source: '高考真题',
      year: 2021,
      region: '全国甲卷',
      subject: 'chinese',
      type: '议论文',
      title: '可为与有为',
      description: '1917年4月，毛泽东在《新青年》发表《体育之研究》一文，其中论及\"体育之效\"时提到：人的身体会天天变化...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['体育', '变化', '坚持']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-007',
      source: '高考真题',
      year: 2021,
      region: '新高考I卷',
      subject: 'chinese',
      type: '议论文',
      title: '生逢其时，重任在肩',
      description: '1917年4月，毛泽东在《新青年》发表《体育之研究》一文，其中论及\"体育之效\"时，提到：人的身体会天天变化...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['时代', '责任', '青年']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-008',
      source: '高考真题',
      year: 2020,
      region: '全国I卷',
      subject: 'chinese',
      type: '议论文',
      title: '关于\"齐桓公、管仲、鲍叔牙\"的思考',
      description: '春秋时期，齐国的公子纠与公子小白争夺君位，管仲和鲍叔牙分别辅佐二人。最后公子小白即位为齐桓公...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['历史', '人才', '品德']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-009',
      source: '高考真题',
      year: 2019,
      region: '全国I卷',
      subject: 'chinese',
      type: '议论文',
      title: '热爱劳动，从我做起',
      description: '\"民生在勤，勤则不匮。\"劳动是财富的源泉，也是幸福的源泉。人世间的美好梦想，都是通过劳动实现的...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['劳动', '奋斗', '实践']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-010',
      source: '高考真题',
      year: 2018,
      region: '全国I卷',
      subject: 'chinese',
      type: '议论文',
      title: '写给未来2035年的那个他',
      description: '2000年农历庚辰龙年，人类迈进新千年，中国千万\"世纪宝宝\"出生。2008年汶川大地震，北京奥运会...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['时代', '发展', '未来']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-011',
      source: '高考真题',
      year: 2017,
      region: '全国I卷',
      subject: 'chinese',
      type: '议论文',
      title: '据近期一项对来华留学生的调查，他们较为关注的\"中国关键词\"',
      description: '请从中选择两三个关键词来呈现你所认识的中国，写一篇文章帮助外国青年读懂中国。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['文化', '国际', '交流']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-012',
      source: '高考真题',
      year: 2016,
      region: '全国I卷',
      subject: 'chinese',
      type: '议论文',
      title: '奖惩之后',
      description: '阅读下面的漫画材料，根据要求写一篇不少于800字的文章。漫画内容：两个孩子考试后，一个考了100分得到表扬，另一个考了55分得到批评...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['教育', '评价', '成长']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-013',
      source: '高考真题',
      year: 2025,
      region: '全国甲卷',
      subject: 'chinese',
      type: '议论文',
      title: '以工匠精神雕琢时代品质',
      description: '工匠精神是对工作的执着，对所做的事情和生产的产品的精雕细琢、精益求精的精神理念。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['工匠精神', '品质', '时代']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-014',
      source: '高考真题',
      year: 2024,
      region: '新课标I卷',
      subject: 'chinese',
      type: '议论文',
      title: '问题与答案',
      description: '随着互联网的普及，人工智能的应用，越来越多的问题能很快得到答案。那么，我们的问题是否会越来越少？',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['互联网', '人工智能', '思考']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-arg-015',
      source: '高考真题',
      year: 2024,
      region: '新课标II卷',
      subject: 'chinese',
      type: '议论文',
      title: '关于\"嫦娥四号\"和\"天问一号\"的思考',
      description: '嫦娥四号探月任务揭开了月背的神秘面纱；天问一号探测器着陆火星，迈出了我国星际探测征程的重要一步...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['科技', '探索', '航天']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== Chinese Topics (记叙文) ==========
  const chineseNarrativeTopics = [
    {
      id: 'cn-nar-001',
      source: '高考真题',
      year: 2023,
      region: '全国乙卷',
      subject: 'chinese',
      type: '记叙文',
      title: '一花独放不是春',
      description: '一朵花的绽放点缀不了整个春天，百花齐放才能展现春天的美丽。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['团结', '合作', '分享']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-002',
      source: '高考真题',
      year: 2022,
      region: '全国乙卷',
      subject: 'chinese',
      type: '记叙文',
      title: '跨越，再跨越',
      description: '双奥之城，闪耀世界。两次奥运会，都显示了中国体育发展的新高度，展示了中国综合国力的跨越式发展...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['奥运', '跨越', '发展']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-003',
      source: '高考真题',
      year: 2021,
      region: '全国乙卷',
      subject: 'chinese',
      type: '记叙文',
      title: '关于理想的思考',
      description: '古人常以比喻说明对理想的追求，涉及基础、方法、路径、目标及其关系等。如汉代扬雄就曾以射箭为喻...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['理想', '追求', '成长']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-004',
      source: '高考真题',
      year: 2020,
      region: '全国II卷',
      subject: 'chinese',
      type: '记叙文',
      title: '携手同一世界，青年共创未来',
      description: '世界青年与发展论坛即将在北京举行，你将在论坛上发表演讲。请结合材料写一篇演讲稿。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['青年', '世界', '合作']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-005',
      source: '高考真题',
      year: 2019,
      region: '全国II卷',
      subject: 'chinese',
      type: '记叙文',
      title: '1949年2019年2049年',
      description: '1949年10月1日，报刊发表《故宫的意义》一文。2019年9月，你将参加\"我和我的祖国\"主题征文活动。2049年9月...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['祖国', '历史', '展望']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-006',
      source: '高考真题',
      year: 2018,
      region: '全国III卷',
      subject: 'chinese',
      type: '记叙文',
      title: '我与高考',
      description: '时间就是金钱，效率就是生命——深圳蛇口工业区标语。绿水青山就是金山银山——浙江余村。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['高考', '青春', '成长']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-007',
      source: '高考真题',
      year: 2017,
      region: '全国III卷',
      subject: 'chinese',
      type: '记叙文',
      title: '我的高考',
      description: '今年是我国恢复高考40周年。40年来，高考为国家选拔了大批人才，无数人通过高考改变了命运。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['高考', '改变命运', '教育']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-008',
      source: '高考真题',
      year: 2016,
      region: '全国III卷',
      subject: 'chinese',
      type: '记叙文',
      title: '小羽的创业故事',
      description: '历经几年试验，小羽在传统工艺的基础上推陈出新，研发出一种新式花茶并获得专利。可是批量生产不久...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['创新', '创业', '分享']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-009',
      source: '高考真题',
      year: 2015,
      region: '全国I卷',
      subject: 'chinese',
      type: '记叙文',
      title: '关于\"小陈举报老陈\"的思考',
      description: '因父亲总是在高速路上开车时接电话，家人屡劝不止，女大学生小陈迫于无奈、出于安全考虑，通过微博私信向警方举报了自己的父亲...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['法律', '亲情', '安全']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-nar-010',
      source: '高考真题',
      year: 2015,
      region: '全国II卷',
      subject: 'chinese',
      type: '记叙文',
      title: '谁最有风采',
      description: '当代风采人物评选活动已进入最后的投票阶段。三位候选人分别是：大李——笃学敏思，矢志创新，率领团队一举跻身生物科技国际前列...',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['风采', '创新', '奉献']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== Chinese Topics (散文/应用文) ==========
  const chineseProseTopics = [
    {
      id: 'cn-pro-001',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'chinese',
      type: '散文',
      title: '乡愁与远方',
      description: '每个人心中都有一个远方，而乡愁是连接过去与未来的桥梁。请以\"乡愁与远方\"为主题，写一篇散文。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['乡愁', '远方', '情感']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-002',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'chinese',
      type: '散文',
      title: '四季之歌',
      description: '春夏秋冬，四季轮回，每个季节都有独特的美。请以四季为线索，写一篇散文。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['四季', '自然', '美']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-003',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'chinese',
      type: '应用文',
      title: '关于校园读书节的倡议书',
      description: '学校将举办校园读书节，请你以学生会的名义写一封倡议书，号召全校同学积极参与。',
      requirements: '不少于800字，格式正确，语言得体',
      tags: JSON.stringify(['倡议书', '读书', '校园']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-004',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'chinese',
      type: '散文',
      title: '老街的记忆',
      description: '城市的老街承载着历史的记忆和文化的积淀。请以\"老街的记忆\"为题，写一篇散文。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['老街', '记忆', '文化']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-005',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'chinese',
      type: '议论文',
      title: '网络时代的阅读',
      description: '在信息爆炸的网络时代，纸质阅读和电子阅读哪个更好？请就这一话题发表你的看法。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['阅读', '网络', '传统']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-006',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'chinese',
      type: '记叙文',
      title: '一次特别的经历',
      description: '每个人都会有一些特别的经历，它们或让你成长，或让你感悟。请记叙一次你特别的经历。',
      requirements: '不少于800字，叙事清楚，描写生动',
      tags: JSON.stringify(['经历', '成长', '感悟']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-007',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'chinese',
      type: '议论文',
      title: '传统文化的传承与创新',
      description: '在现代社会中，如何传承和创新传统文化是一个重要课题。请就传统文化的传承与创新发表你的看法。',
      requirements: '不少于800字，自选角度，自拟题目',
      tags: JSON.stringify(['传统文化', '传承', '创新']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'cn-pro-008',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'chinese',
      type: '记叙文',
      title: '那一刻，我长大了',
      description: '成长的路上，总有一些特别的时刻让我们突然意识到自己已经长大。请记叙这样一个时刻。',
      requirements: '不少于800字，叙事清楚，感情真挚',
      tags: JSON.stringify(['成长', '感悟', '青春']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== English Topics (书信) ==========
  const englishLetterTopics = [
    {
      id: 'en-letter-001',
      source: '高考真题',
      year: 2024,
      region: '全国甲卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to a Foreign Friend',
      description: 'Write a letter to a foreign friend to introduce your favorite Chinese tradition.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'tradition', 'culture']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-002',
      source: '高考真题',
      year: 2023,
      region: '全国甲卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to Chris',
      description: 'Your foreign friend Chris plans to visit China and asks for your advice on what to see and do.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'travel', 'advice']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-003',
      source: '高考真题',
      year: 2022,
      region: '全国甲卷',
      subject: 'english',
      type: '书信',
      title: 'Letter about Learning Chinese',
      description: 'Write a letter to your foreign friend who is learning Chinese, sharing your learning experience and tips.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'learning', 'Chinese']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-004',
      source: '高考真题',
      year: 2021,
      region: '全国甲卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to a Foreign Teacher',
      description: 'Write a letter to your foreign teacher to thank him/her for the help during your study.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'thank', 'teacher']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-005',
      source: '高考真题',
      year: 2020,
      region: '全国I卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to Jim',
      description: 'Your foreign friend Jim wants to learn Chinese calligraphy. Write a letter to give him some advice.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'calligraphy', 'advice']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-006',
      source: '高考真题',
      year: 2019,
      region: '全国I卷',
      subject: 'english',
      type: '书信',
      title: 'Letter about Volunteering',
      description: 'Write a letter to your foreign friend Peter who is interested in volunteering in China.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'volunteering', 'community']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-007',
      source: '高考真题',
      year: 2018,
      region: '全国I卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to Bob',
      description: 'Write a letter to your foreign friend Bob to introduce a Chinese dish you know how to cook.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'cooking', 'food']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-008',
      source: '高考真题',
      year: 2017,
      region: '全国I卷',
      subject: 'english',
      type: '书信',
      title: 'Letter to外国笔友',
      description: 'Write a letter to your foreign pen pal to tell him/her about your school life.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'school', 'life']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-009',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'english',
      type: '书信',
      title: 'Letter to Future Self',
      description: 'Write a letter to your future self, reflecting on your current life and hopes for the future.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'future', 'reflection']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-letter-010',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'english',
      type: '书信',
      title: 'Recommendation Letter',
      description: 'Write a letter to recommend a book/movie to your foreign friend.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['letter', 'recommendation', 'book']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== English Topics (通知/演讲) ==========
  const englishNoticeTopics = [
    {
      id: 'en-notice-001',
      source: '高考真题',
      year: 2023,
      region: '新课标I卷',
      subject: 'english',
      type: '通知',
      title: 'Notice about English Speech Contest',
      description: 'You are the president of the Student Union. Write a notice about the upcoming English Speech Contest.',
      requirements: 'About 100 words',
      tags: JSON.stringify(['notice', 'speech', 'contest']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-notice-002',
      source: '高考真题',
      year: 2022,
      region: '新课标I卷',
      subject: 'english',
      type: '通知',
      title: 'Notice about Sports Day',
      description: 'Write a notice to inform students about the annual Sports Day and encourage participation.',
      requirements: 'About 100 words',
      tags: JSON.stringify(['notice', 'sports', 'activity']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-notice-003',
      source: '高考真题',
      year: 2021,
      region: '新课标I卷',
      subject: 'english',
      type: '通知',
      title: 'Notice about Library Hours',
      description: 'Write a notice to inform students about changes to library opening hours during exam period.',
      requirements: 'About 100 words',
      tags: JSON.stringify(['notice', 'library', 'exam']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-speech-001',
      source: '高考真题',
      year: 2024,
      region: '新课标II卷',
      subject: 'english',
      type: '演讲',
      title: 'Speech about Environmental Protection',
      description: 'Write a speech for the school environmental protection day.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['speech', 'environment', 'protection']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-speech-002',
      source: '高考真题',
      year: 2023,
      region: '新课标II卷',
      subject: 'english',
      type: '演讲',
      title: 'Speech about Friendship',
      description: 'Write a speech about the importance of friendship for the class meeting.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['speech', 'friendship', 'class']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-speech-003',
      source: '高考真题',
      year: 2022,
      region: '新课标II卷',
      subject: 'english',
      type: '演讲',
      title: 'Speech about Healthy Living',
      description: 'Write a speech about maintaining a healthy lifestyle for the school health week.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['speech', 'health', 'lifestyle']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-speech-004',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'english',
      type: '演讲',
      title: 'Speech about Digital Literacy',
      description: 'Write a speech about the importance of digital literacy in the modern world.',
      requirements: 'About 120 words',
      tags: JSON.stringify(['speech', 'digital', 'literacy']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== English Topics (读后续写) ==========
  const englishContinuationTopics = [
    {
      id: 'en-cont-001',
      source: '高考真题',
      year: 2024,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'A Vacation with My Mother',
      description: 'I had an interesting childhood. It was filled with surprises and adventures, most of which involved my mother.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'family', 'vacation']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-002',
      source: '高考真题',
      year: 2023,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'The Writing on the Wall',
      description: 'I was in a terrible hurry as I went to attend a meeting. As I rushed to get into the elevator, I bumped into an old man.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'encounter', 'kindness']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-003',
      source: '高考真题',
      year: 2022,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'A Race Against Time',
      description: 'It was the day of the big cross-country race. Students from all over the school gathered at the starting line.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'race', 'perseverance']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-004',
      source: '高考真题',
      year: 2021,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'The Bucket List',
      description: 'My dad was a farmer and so were all his before him. But I had bigger dreams. I was going to be a millionaire.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'dreams', 'family']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-005',
      source: '高考真题',
      year: 2020,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'The Christmas Presentation',
      description: 'It was Christmas morning and my wife and I were excited. We watched as our children came running downstairs.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'Christmas', 'family']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-006',
      source: '高考真题',
      year: 2019,
      region: '新课标I卷',
      subject: 'english',
      type: '读后续写',
      title: 'The Brown Bag',
      description: 'I had an interesting experience last year. I was walking past a school when I noticed a brown bag on the ground.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'mystery', 'discovery']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-007',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'english',
      type: '读后续写',
      title: 'Lost in the Forest',
      description: 'My friend Jack and I went hiking in the mountains last summer. One afternoon, we decided to explore a path we had never taken before.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'adventure', 'friendship']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-008',
      source: '模拟题',
      year: 2025,
      region: null,
      subject: 'english',
      type: '读后续写',
      title: 'The New Neighbor',
      description: 'We had a new neighbor move in next door. She was an elderly woman who seemed to live alone.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'neighbor', 'kindness']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-009',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'english',
      type: '读后续写',
      title: 'A Rainy Day Surprise',
      description: 'It was a rainy Monday morning. I forgot my umbrella and was hurrying to school when something unexpected happened.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'rain', 'surprise']),
      sampleEssays: JSON.stringify([]),
    },
    {
      id: 'en-cont-010',
      source: '模拟题',
      year: 2024,
      region: null,
      subject: 'english',
      type: '读后续写',
      title: 'The Old Photograph',
      description: 'While cleaning out the attic, I found an old photograph of my grandparents. On the back was written a date and a short message.',
      requirements: 'About 150 words',
      tags: JSON.stringify(['continuation', 'photograph', 'memory']),
      sampleEssays: JSON.stringify([]),
    },
  ]

  // ========== Diagnostic Questions ==========
  const diagnosticQuestions = [
    // 审题立意 (Direction/Understanding) - 5 questions
    {
      id: 'diag-001',
      type: 'direction',
      question: '阅读下面的材料，选择一个角度确定立意。"水滴石穿，绳锯木断。"',
      options: JSON.stringify(['坚持不懈终会成功', '水很厉害', '石头不结实', '绳子质量好']),
      correctAnswer: 0,
      explanation: '这则材料强调的是持之以恒的精神，只有坚持不懈才能取得成功。',
      score: 20,
    },
    {
      id: 'diag-002',
      type: 'direction',
      question: '以下哪个题目最适合写一篇议论文？',
      options: JSON.stringify(['我的一天', '论科技与生活', '妈妈的手', '校园一角']),
      correctAnswer: 1,
      explanation: '"论科技与生活"明确提出了议论的话题，适合写议论文。',
      score: 20,
    },
    {
      id: 'diag-003',
      type: 'direction',
      question: '"纸上得来终觉浅，绝知此事要躬行"这句话强调的是什么？',
      options: JSON.stringify(['读书没用', '实践的重要性', '要多写作文', '理论比实践重要']),
      correctAnswer: 1,
      explanation: '这句话出自陆游的《冬夜读书示子聿》，强调实践的重要性。',
      score: 20,
    },
    {
      id: 'diag-004',
      type: 'direction',
      question: '写一篇关于"诚信"的文章，以下哪个立意最深刻？',
      options: JSON.stringify(['诚信就是不说谎', '诚信是做人的根本', '诚信需要勇气', '做生意要讲诚信']),
      correctAnswer: 1,
      explanation: '"诚信是做人的根本"立意最为深刻，从做人的本质高度来论述。',
      score: 20,
    },
    {
      id: 'diag-005',
      type: 'direction',
      question: '材料作文中，如何确定最佳立意？',
      options: JSON.stringify(['随便选一个角度', '选择自己最熟悉的角度', '分析材料的核心观点', '选择最简单的角度']),
      correctAnswer: 2,
      explanation: '分析材料的核心观点才能找到最佳立意，确保不偏题。',
      score: 20,
    },
    // 段落排序 (Structure) - 5 questions
    {
      id: 'diag-006',
      type: 'structure',
      question: '议论文的基本结构是什么？',
      options: JSON.stringify(['开头-中间-结尾', '提出问题-分析问题-解决问题', '时间顺序-地点顺序-人物顺序', '总-分-总']),
      correctAnswer: 1,
      explanation: '议论文的基本结构是"提出问题-分析问题-解决问题"，即"是什么-为什么-怎么办"。',
      score: 20,
    },
    {
      id: 'diag-007',
      type: 'structure',
      question: '以下哪段话适合作为文章的结尾？',
      options: JSON.stringify([
        '总之，我们每个人都应该认识到诚信的重要性，从身边小事做起，做一个诚信的人。',
        '诚信就是诚实守信，是中华民族的传统美德。',
        '古时候有一个故事叫"狼来了"，告诉我们做人要诚实。',
        '有人说诚信很重要，有人说诚信不重要。',
      ]),
      correctAnswer: 0,
      explanation: '结尾段应该总结全文、升华主题，选项A符合结尾段的特点。',
      score: 20,
    },
    {
      id: 'diag-008',
      type: 'structure',
      question: '文章开头段的主要作用是什么？',
      options: JSON.stringify(['详细论述观点', '引出话题、提出论点', '总结全文', '举例论证']),
      correctAnswer: 1,
      explanation: '开头段的作用是引出话题、提出中心论点，为后文的论述做铺垫。',
      score: 20,
    },
    {
      id: 'diag-009',
      type: 'structure',
      question: '在议论文中，如何安排论据的顺序？',
      options: JSON.stringify(['随便排列', '按照时间顺序', '按照重要程度排列', '按照字数多少排列']),
      correctAnswer: 2,
      explanation: '论据应该按照重要程度排列，最重要的论据放在最前面，这样更有说服力。',
      score: 20,
    },
    {
      id: 'diag-010',
      type: 'structure',
      question: '以下哪个段落结构最合理？',
      options: JSON.stringify([
        '论点→论据→分析→小结',
        '论据→论点→分析→小结',
        '小结→论点→论据→分析',
        '分析→论据→论点→小结',
      ]),
      correctAnswer: 0,
      explanation: '标准的段落结构是：先提出论点，然后用论据证明，接着分析论据，最后小结。',
      score: 20,
    },
    // 词汇选择 (Vocabulary) - 5 questions
    {
      id: 'diag-011',
      type: 'vocab',
      question: '以下哪个词语使用最恰当？"他的演讲______了在场所有人。"',
      options: JSON.stringify(['感动', '打动', '激动', '震动']),
      correctAnswer: 1,
      explanation: '"打动"最合适，表示演讲触动了人们的情感。"感动"一般用于被动句。',
      score: 20,
    },
    {
      id: 'diag-012',
      type: 'vocab',
      question: '"这本书的内容非常______，值得一读。"',
      options: JSON.stringify(['丰富', '很多', '不少', '大量']),
      correctAnswer: 0,
      explanation: '"丰富"最恰当，形容内容充实、多彩。"很多"、"不少"、"大量"都不够书面化。',
      score: 20,
    },
    {
      id: 'diag-013',
      type: 'vocab',
      question: '以下哪个成语使用正确？',
      options: JSON.stringify([
        '他的文章写得栩栩如生。',
        '他的想法异想天开。',
        '他的成绩名列前茅。',
        '他的行为令人发指。',
      ]),
      correctAnswer: 2,
      explanation: '"名列前茅"使用正确，表示成绩优秀，排名靠前。"栩如生"一般形容艺术品。',
      score: 20,
    },
    {
      id: 'diag-014',
      type: 'vocab',
      question: '"面对困难，我们不能______，要勇敢面对。"',
      options: JSON.stringify(['退缩', '后退', '逃跑', '躲避']),
      correctAnswer: 0,
      explanation: '"退缩"最合适，表示在困难面前畏缩不前。"逃跑"、"躲避"语气过重。',
      score: 20,
    },
    {
      id: 'diag-015',
      type: 'vocab',
      question: '以下哪组词语搭配最恰当？',
      options: JSON.stringify([
        '提高水平、增强能力',
        '提高能力、增强水平',
        '提升水平、提高能力',
        '增强水平、提升能力',
      ]),
      correctAnswer: 0,
      explanation: '"提高水平、增强能力"搭配最恰当，符合汉语的搭配习惯。',
      score: 20,
    },
    // 句式改写 (Sentence) - 5 questions
    {
      id: 'diag-016',
      type: 'sentence',
      question: '将"我们一定要努力学习"改为更有力的表达方式。',
      options: JSON.stringify([
        '我们必须努力学习。',
        '我们不得不努力学习。',
        '我们应该努力学习。',
        '我们想要努力学习。',
      ]),
      correctAnswer: 0,
      explanation: '"必须"比"一定要"更有力度，表达了强烈的决心和必要性。',
      score: 20,
    },
    {
      id: 'diag-017',
      type: 'sentence',
      question: '以下哪个句子表达最准确？',
      options: JSON.stringify([
        '通过这次活动，使我们认识到了团结的重要性。',
        '通过这次活动，我们认识到了团结的重要性。',
        '这次活动，使我们认识到了团结的重要性。',
        '这次活动，让我们认识到了团结的重要性。',
      ]),
      correctAnswer: 1,
      explanation: '选项B语法正确，主语明确。A和C缺少主语，D的"让"不如"使"正式。',
      score: 20,
    },
    {
      id: 'diag-018',
      type: 'sentence',
      question: '如何将陈述句改写为反问句以增强表达效果？',
      options: JSON.stringify([
        '"我们应该珍惜时间"→"我们难道不应该珍惜时间吗？"',
        '"我们应该珍惜时间"→"我们珍惜时间吗？"',
        '"我们应该珍惜时间"→"我们珍惜时间！"',
        '"我们应该珍惜时间"→"我们一定要珍惜时间。"',
      ]),
      correctAnswer: 0,
      explanation: '反问句通过"难道...吗？"的结构增强语气，表达更强烈的肯定或否定。',
      score: 20,
    },
    {
      id: 'diag-019',
      type: 'sentence',
      question: '以下哪个句子使用了排比修辞手法？',
      options: JSON.stringify([
        '爱心是一片照射在冬日的阳光，爱心是一泓出现在沙漠里的泉水，爱心是一首飘荡在夜空的歌谣。',
        '他的眼睛像星星一样明亮。',
        '时间就是金钱，效率就是生命。',
        '春天来了，花儿开了，鸟儿叫了。',
      ]),
      correctAnswer: 0,
      explanation: '选项A使用了三个结构相似的比喻句构成排比，增强了表达的气势和感染力。',
      score: 20,
    },
    {
      id: 'diag-020',
      type: 'sentence',
      question: '将"因为下雨，所以比赛取消了"改写得更加简洁有力。',
      options: JSON.stringify([
        '由于下雨，比赛取消了。',
        '比赛因雨取消。',
        '下雨了，比赛取消了。',
        '比赛取消了，因为下雨。',
      ]),
      correctAnswer: 1,
      explanation: '"比赛因雨取消"最为简洁有力，省去了不必要的词语，表达直接明了。',
      score: 20,
    },
    // 找错误 (Error Finding) - 5 questions
    {
      id: 'diag-021',
      type: 'error',
      question: '以下哪个句子有语病？',
      options: JSON.stringify([
        '他的学习成绩一直在不断进步。',
        '我们要发扬和继承优良传统。',
        '他的演讲赢得了全场热烈的掌声。',
        '这本书的内容非常丰富。',
      ]),
      correctAnswer: 1,
      explanation: '语序不当，应该先"继承"后"发扬"，符合事物发展的逻辑顺序。',
      score: 20,
    },
    {
      id: 'diag-022',
      type: 'error',
      question: '找出以下句子中的错误："通过老师的帮助，使我的成绩提高了。"',
      options: JSON.stringify([
        '缺少主语',
        '用词不当',
        '语序混乱',
        '标点错误',
      ]),
      correctAnswer: 0,
      explanation: '"通过...使..."的句式导致句子缺少主语，应该删去"通过"或"使"。',
      score: 20,
    },
    {
      id: 'diag-023',
      type: 'error',
      question: '以下哪个句子没有语病？',
      options: JSON.stringify([
        '他不但学习成绩好，而且品德优秀。',
        '他的作文写得很优美、整洁。',
        '这篇文章的内容和形式都很丰富。',
        '他基本上把所有的作业都做完了。',
      ]),
      correctAnswer: 0,
      explanation: '选项A语句通顺，逻辑清晰。B中"优美"不能形容"整洁"；C中"形式"不能用"丰富"形容；D中"基本上"和"所有"矛盾。',
      score: 20,
    },
    {
      id: 'diag-024',
      type: 'error',
      question: '以下句子中，哪个使用了正确的标点符号？',
      options: JSON.stringify([
        '他说："今天天气真好。"',
        '他说"今天天气真好"。',
        '他说：今天天气真好。',
        '他说，今天天气真好。',
      ]),
      correctAnswer: 0,
      explanation: '选项A使用了正确的冒号和引号格式，符合中文标点符号规范。',
      score: 20,
    },
    {
      id: 'diag-025',
      type: 'error',
      question: '"这次考试，我们班同学的成绩都很好，没有一个不及格的。"这个句子的问题是什么？',
      options: JSON.stringify([
        '语义重复',
        '前后矛盾',
        '搭配不当',
        '成分残缺',
      ]),
      correctAnswer: 1,
      explanation: '"都很好"和"没有一个不及格的"语义重复，应该删去其中一个。',
      score: 20,
    },
    // 英语诊断题 (English) - 5 questions
    {
      id: 'diag-026',
      type: 'direction',
      question: 'Which of the following is the correct format for an English formal letter?',
      options: JSON.stringify([
        'Dear Sir/Madam, ... Yours sincerely, [Name]',
        'Hey, ... See ya, [Name]',
        'To whom it may concern, ... Bye, [Name]',
        'Hi there, ... Cheers, [Name]',
      ]),
      correctAnswer: 0,
      explanation: 'A formal letter should start with "Dear Sir/Madam" and end with "Yours sincerely" or "Yours faithfully".',
      score: 20,
    },
    {
      id: 'diag-027',
      type: 'vocab',
      question: 'Choose the correct word: "I am writing to ____ you about the upcoming event."',
      options: JSON.stringify(['inform', 'tell', 'say', 'speak']),
      correctAnswer: 0,
      explanation: '"Inform" is the most appropriate word for formal communication about providing information.',
      score: 20,
    },
    {
      id: 'diag-028',
      type: 'structure',
      question: 'In a continuation writing task, what is the most important thing to maintain?',
      options: JSON.stringify([
        'Consistency with the original text',
        'Using difficult vocabulary',
        'Writing as many words as possible',
        'Including many dialogue lines',
      ]),
      correctAnswer: 0,
      explanation: 'Consistency with the original text in terms of tone, style, and plot is the most important.',
      score: 20,
    },
    {
      id: 'diag-029',
      type: 'sentence',
      question: 'Which sentence uses the correct conditional structure?',
      options: JSON.stringify([
        'If I were you, I would study harder.',
        'If I was you, I would study harder.',
        'If I am you, I would study harder.',
        'If I be you, I would study harder.',
      ]),
      correctAnswer: 0,
      explanation: 'The second conditional uses "were" for all persons, including "I" and "he/she/it".',
      score: 20,
    },
    {
      id: 'diag-030',
      type: 'error',
      question: 'Find the error: "Neither the teacher nor the students was able to solve the problem."',
      options: JSON.stringify([
        'was should be were',
        'Neither should be Either',
        'nor should be or',
        'the should be a',
      ]),
      correctAnswer: 0,
      explanation: 'With "neither...nor...", the verb agrees with the nearest subject. "Students" is plural, so "were" should be used.',
      score: 20,
    },
    {
      id: 'diag-031',
      type: 'direction',
      question: 'When writing a speech, what should you include at the beginning?',
      options: JSON.stringify([
        'A greeting and introduction of the topic',
        'A detailed conclusion',
        'A list of references',
        'Statistical data',
      ]),
      correctAnswer: 0,
      explanation: 'A speech should start with a greeting to the audience and a clear introduction of the topic.',
      score: 20,
    },
    {
      id: 'diag-032',
      type: 'vocab',
      question: 'Which word best completes: "The government has ____ new policies to protect the environment."',
      options: JSON.stringify(['implemented', 'made', 'done', 'put']),
      correctAnswer: 0,
      explanation: '"Implemented" is the correct collocate with "policies", meaning to put into effect.',
      score: 20,
    },
    {
      id: 'diag-033',
      type: 'structure',
      question: 'How many paragraphs are typically needed for an English argumentative essay (about 120 words)?',
      options: JSON.stringify(['3-4 paragraphs', '1-2 paragraphs', '5-6 paragraphs', '7-8 paragraphs']),
      correctAnswer: 0,
      explanation: 'An argumentative essay of about 120 words typically has 3-4 paragraphs: introduction, body, and conclusion.',
      score: 20,
    },
    {
      id: 'diag-034',
      type: 'sentence',
      question: 'Which is the correct way to express emphasis?',
      options: JSON.stringify([
        'It is important that we study hard.',
        'We study hard is important.',
        'Important we study hard.',
        'We is important study hard.',
      ]),
      correctAnswer: 0,
      explanation: 'The cleft sentence "It is important that..." is the correct structure for emphasis.',
      score: 20,
    },
    {
      id: 'diag-035',
      type: 'error',
      question: 'Which sentence has correct subject-verb agreement?',
      options: JSON.stringify([
        'The group of students are going on a field trip.',
        'Each of the students have a textbook.',
        'Neither the cat nor the dogs was found.',
        'Everyone is responsible for their own actions.',
      ]),
      correctAnswer: 3,
      explanation: 'Option D is correct. "Everyone" is singular, and "is" agrees with it.',
      score: 20,
    },
  ]

  // Insert all topics
  const allTopics = [
    ...chineseArgumentativeTopics,
    ...chineseNarrativeTopics,
    ...chineseProseTopics,
    ...englishLetterTopics,
    ...englishNoticeTopics,
    ...englishContinuationTopics,
  ]

  console.log(`Inserting ${allTopics.length} topics...`)

  for (const topic of allTopics) {
    await prisma.topic.create({ data: topic })
  }

  console.log('Topics inserted successfully!')

  // Insert diagnostic questions
  console.log(`Inserting ${diagnosticQuestions.length} diagnostic questions...`)

  // Store diagnostic questions as a special topic
  await prisma.topic.create({
    data: {
      id: 'diagnostic-questions',
      source: '系统内置',
      year: null,
      region: null,
      subject: 'mixed',
      type: '诊断题',
      title: '入学诊断测试题',
      description: '用于评估学生在审题立意、段落排序、词汇选择、句式改写和找错误五个维度的能力水平',
      requirements: '共35题，每题20分，满分700分',
      tags: JSON.stringify(['诊断', '评估', '能力测试']),
      sampleEssays: JSON.stringify(diagnosticQuestions),
    },
  })

  console.log('Diagnostic questions inserted!')

  // ========== Materials ==========
  const materials = [
    // ---- Chinese 论据 (Arguments) ----
    { userId: 'demo-user', content: '司马迁遭受宫刑之辱，却忍辱负重，以"究天人之际，通古今之变，成一家之言"的信念，历时十余年写成"史家之绝唱，无韵之离骚"的《史记》。', source: '范文', category: '论据', subject: 'chinese', tags: ['司马迁', '坚持', '逆境'], usageCount: 5 },
    { userId: 'demo-user', content: '屠呦呦团队历经190次失败，从青蒿中提取出青蒿素，挽救了全球数百万疟疾患者的生命，获得诺贝尔生理学或医学奖。', source: '范文', category: '论据', subject: 'chinese', tags: ['屠呦呦', '科研', '坚持'], usageCount: 3 },
    { userId: 'demo-user', content: '苏轼一生三次被贬，却在逆境中写下"竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生"的豁达诗句，展现了中国文人的精神风骨。', source: '范文', category: '论据', subject: 'chinese', tags: ['苏轼', '豁达', '逆境'], usageCount: 4 },
    { userId: 'demo-user', content: '袁隆平扎根稻田五十余年，培育出杂交水稻，让中国人端稳了自己的饭碗，被誉为"杂交水稻之父"。', source: '范文', category: '论据', subject: 'chinese', tags: ['袁隆平', '奉献', '科技'], usageCount: 6 },
    { userId: 'demo-user', content: '张桂梅创办华坪女子高中，帮助近2000名贫困山区女孩走出大山、走进大学，用教育阻断贫困代际传递。', source: 'AI推荐', category: '论据', subject: 'chinese', tags: ['张桂梅', '教育', '奉献'], usageCount: 2 },
    { userId: 'demo-user', content: '敦煌研究院名誉院长樊锦诗，扎根大漠五十余年，推动"数字敦煌"建设，让千年壁画永续保存。', source: '范文', category: '论据', subject: 'chinese', tags: ['樊锦诗', '敦煌', '文化传承'], usageCount: 1 },
    { userId: 'demo-user', content: '黄大年放弃海外优厚待遇毅然回国，带领团队攻克深地探测关键技术，为中国地球物理事业作出卓越贡献。', source: 'AI推荐', category: '论据', subject: 'chinese', tags: ['黄大年', '爱国', '科技'], usageCount: 2 },

    // ---- Chinese 名言 (Quotes) ----
    { userId: 'demo-user', content: '"路漫漫其修远兮，吾将上下而求索。" ——屈原《离骚》', source: '范文', category: '名言', subject: 'chinese', tags: ['屈原', '求索', '坚持'], usageCount: 8 },
    { userId: 'demo-user', content: '"天行健，君子以自强不息。" ——《周易》', source: '范文', category: '名言', subject: 'chinese', tags: ['自强', '古典', '奋斗'], usageCount: 7 },
    { userId: 'demo-user', content: '"博学之，审问之，慎思之，明辨之，笃行之。" ——《中庸》', source: '范文', category: '名言', subject: 'chinese', tags: ['学习', '实践', '古典'], usageCount: 5 },
    { userId: 'demo-user', content: '"纸上得来终觉浅，绝知此事要躬行。" ——陆游', source: '范文', category: '名言', subject: 'chinese', tags: ['实践', '知行合一'], usageCount: 6 },
    { userId: 'demo-user', content: '"宝剑锋从磨砺出，梅花香自苦寒来。" ——《警世贤文》', source: '范文', category: '名言', subject: 'chinese', tags: ['磨砺', '逆境', '成功'], usageCount: 4 },
    { userId: 'demo-user', content: '"千磨万击还坚劲，任尔东西南北风。" ——郑燮《竹石》', source: 'AI推荐', category: '名言', subject: 'chinese', tags: ['坚韧', '品格', '逆境'], usageCount: 3 },
    { userId: 'demo-user', content: '"长风破浪会有时，直挂云帆济沧海。" ——李白《行路难》', source: '范文', category: '名言', subject: 'chinese', tags: ['李白', '自信', '理想'], usageCount: 5 },
    { userId: 'demo-user', content: '"不积跬步，无以至千里；不积小流，无以成江海。" ——荀子《劝学》', source: '范文', category: '名言', subject: 'chinese', tags: ['积累', '坚持', '荀子'], usageCount: 6 },

    // ---- Chinese 事例 (Examples) ----
    { userId: 'demo-user', content: '2024年嫦娥六号实现世界首次月球背面采样返回，标志着中国航天从"跟跑"到"领跑"的跨越。', source: 'AI推荐', category: '事例', subject: 'chinese', tags: ['航天', '科技', '创新'], usageCount: 3 },
    { userId: 'demo-user', content: '华为面对芯片封锁，自主研发鸿蒙操作系统和麒麟芯片，走出了一条自主创新之路。', source: 'AI推荐', category: '事例', subject: 'chinese', tags: ['华为', '自主创新', '科技'], usageCount: 4 },
    { userId: 'demo-user', content: '敦煌莫高窟的"数字敦煌"项目，利用高精度数字技术永久保存壁画，让文化遗产突破时空限制。', source: '范文', category: '事例', subject: 'chinese', tags: ['敦煌', '文化', '科技'], usageCount: 2 },
    { userId: 'demo-user', content: '北京冬奥会开幕式以"二十四节气"倒计时惊艳世界，展现了中华传统文化与现代科技的完美融合。', source: '范文', category: '事例', subject: 'chinese', tags: ['冬奥', '文化', '创新'], usageCount: 3 },
    { userId: 'demo-user', content: '中国高铁从引进消化吸收再创新到完全自主知识产权，运营里程突破4万公里，成为中国制造的金名片。', source: 'AI推荐', category: '事例', subject: 'chinese', tags: ['高铁', '创新', '中国制造'], usageCount: 2 },

    // ---- Chinese 好词好句 (Good Phrases) ----
    { userId: 'demo-user', content: '砥砺前行、踔厉奋发、笃行不怠、赓续传承、守正创新', source: 'AI推荐', category: '好词好句', subject: 'chinese', tags: ['四字词语', '书面语'], usageCount: 10 },
    { userId: 'demo-user', content: '以梦为马、不负韶华；以汗为泉、不负青春。', source: '范文', category: '好词好句', subject: 'chinese', tags: ['青春', '奋斗', '对仗'], usageCount: 7 },
    { userId: 'demo-user', content: '在时代的洪流中，每一个人都是浪花，每一朵浪花都折射着太阳的光芒。', source: 'AI推荐', category: '好词好句', subject: 'chinese', tags: ['比喻', '时代', '个人'], usageCount: 4 },
    { userId: 'demo-user', content: '文化如水，润物无声；传统如灯，照亮前路。', source: '范文', category: '好词好句', subject: 'chinese', tags: ['文化', '比喻', '对仗'], usageCount: 5 },
    { userId: 'demo-user', content: '山河为证，岁月为名；以奋斗致敬时代，以实干书写华章。', source: 'AI推荐', category: '好词好句', subject: 'chinese', tags: ['奋斗', '排比', '书面语'], usageCount: 3 },

    // ---- English 论据 (Arguments) ----
    { userId: 'demo-user', content: 'Steve Jobs was fired from Apple, the company he co-founded, yet he returned to transform it into one of the most valuable companies in the world, proving that failure can be a stepping stone to greater success.', source: '范文', category: '论据', subject: 'english', tags: ['Steve Jobs', 'failure', 'perseverance'], usageCount: 4 },
    { userId: 'demo-user', content: 'Malala Yousafzai, despite being shot by the Taliban for advocating girls\' education, continued her fight and became the youngest Nobel Prize laureate at age 17.', source: '范文', category: '论据', subject: 'english', tags: ['Malala', 'education', 'courage'], usageCount: 3 },
    { userId: 'demo-user', content: 'Thomas Edison conducted over 10,000 experiments before inventing the practical light bulb, demonstrating that persistence in the face of repeated failure is essential for innovation.', source: 'AI推荐', category: '论据', subject: 'english', tags: ['Edison', 'persistence', 'innovation'], usageCount: 5 },
    { userId: 'demo-user', content: 'The Chinese space program\'s success with the Tiangong space station shows how long-term vision and sustained investment can achieve remarkable technological breakthroughs.', source: 'AI推荐', category: '论据', subject: 'english', tags: ['space', 'technology', 'China'], usageCount: 2 },

    // ---- English 名言 (Quotes) ----
    { userId: 'demo-user', content: '"The only way to do great work is to love what you do." ——Steve Jobs', source: '范文', category: '名言', subject: 'english', tags: ['Jobs', 'passion', 'work'], usageCount: 6 },
    { userId: 'demo-user', content: '"In the middle of difficulty lies opportunity." ——Albert Einstein', source: '范文', category: '名言', subject: 'english', tags: ['Einstein', 'difficulty', 'opportunity'], usageCount: 5 },
    { userId: 'demo-user', content: '"Education is the most powerful weapon which you can use to change the world." ——Nelson Mandela', source: '范文', category: '名言', subject: 'english', tags: ['Mandela', 'education', 'change'], usageCount: 7 },
    { userId: 'demo-user', content: '"Success is not final, failure is not fatal: it is the courage to continue that counts." ——Winston Churchill', source: '范文', category: '名言', subject: 'english', tags: ['Churchill', 'courage', 'perseverance'], usageCount: 4 },
    { userId: 'demo-user', content: '"The future belongs to those who believe in the beauty of their dreams." ——Eleanor Roosevelt', source: 'AI推荐', category: '名言', subject: 'english', tags: ['Roosevelt', 'dreams', 'belief'], usageCount: 3 },
    { userId: 'demo-user', content: '"It does not matter how slowly you go as long as you do not stop." ——Confucius', source: '范文', category: '名言', subject: 'english', tags: ['Confucius', 'perseverance', 'progress'], usageCount: 4 },

    // ---- English 事例 (Examples) ----
    { userId: 'demo-user', content: 'The COVID-19 pandemic accelerated the adoption of remote work, fundamentally changing how millions of people around the world approach their careers and work-life balance.', source: 'AI推荐', category: '事例', subject: 'english', tags: ['pandemic', 'remote work', 'change'], usageCount: 2 },
    { userId: 'demo-user', content: 'Greta Thunberg, a Swedish teenager, sparked a global climate movement by staging school strikes, demonstrating that youth can drive meaningful social change.', source: '范文', category: '事例', subject: 'english', tags: ['Thunberg', 'climate', 'youth'], usageCount: 3 },
    { userId: 'demo-user', content: 'The rapid development of artificial intelligence, particularly large language models, is transforming education, healthcare, and creative industries worldwide.', source: 'AI推荐', category: '事例', subject: 'english', tags: ['AI', 'technology', 'transformation'], usageCount: 2 },

    // ---- English 好词好句 (Good Phrases) ----
    { userId: 'demo-user', content: 'It is widely acknowledged that... / There is no denying that... / It goes without saying that...', source: '范文', category: '好词好句', subject: 'english', tags: ['academic', 'essay', 'transition'], usageCount: 9 },
    { userId: 'demo-user', content: 'From my perspective / In my opinion / As far as I am concerned / Personally, I believe that...', source: '范文', category: '好词好句', subject: 'english', tags: ['opinion', 'essay', 'phrase'], usageCount: 8 },
    { userId: 'demo-user', content: 'Not only... but also... / Neither... nor... / Whether... or...', source: 'AI推荐', category: '好词好句', subject: 'english', tags: ['grammar', 'structure', 'parallelism'], usageCount: 5 },
    { userId: 'demo-user', content: 'On the one hand... On the other hand... / In contrast / Conversely / Nevertheless', source: '范文', category: '好词好句', subject: 'english', tags: ['contrast', 'transition', 'essay'], usageCount: 6 },
    { userId: 'demo-user', content: 'A growing number of... / An increasing number of... / The majority of...', source: 'AI推荐', category: '好词好句', subject: 'english', tags: ['quantifier', 'academic', 'writing'], usageCount: 4 },
    { userId: 'demo-user', content: 'Last but not least / In conclusion / To sum up / All things considered', source: '范文', category: '好词好句', subject: 'english', tags: ['conclusion', 'transition', 'essay'], usageCount: 7 },
  ]

  // Create a demo user
  await prisma.user.create({
    data: {
      id: 'demo-user',
      name: 'Demo Student',
      stage: 'sprout',
      chineseLevel: 1,
      englishLevel: 1,
      grade: '高一',
    },
  })

  console.log('Demo user created!')

  console.log(`Inserting ${materials.length} materials...`)

  for (const material of materials) {
    await prisma.material.create({
      data: {
        ...material,
        tags: JSON.stringify(material.tags),
      },
    })
  }

  console.log('Materials inserted successfully!')

  console.log('Database seeded successfully!')
  console.log(`Total topics: ${allTopics.length}`)
  console.log(`Total diagnostic questions: ${diagnosticQuestions.length}`)
  console.log(`Total materials: ${materials.length}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
