export interface ErrorCase {
  id: string
  subject: 'chinese' | 'english'
  category: string
  subType: string
  errorExample: string
  correctedExample: string
  explanation: string
  relatedLevel: string
  severity: 'high' | 'medium' | 'low'
}

// ==================== Chinese Error Cases ====================

const CHINESE_LOGIC_CASES: ErrorCase[] = [
  {
    id: 'cn-logic-1',
    subject: 'chinese',
    category: '逻辑类',
    subType: '偷换概念',
    errorExample: '科技的发展让我们的生活更加便利，所以人工智能会取代所有人类的工作。',
    correctedExample: '科技的发展让我们的生活更加便利，但同时也对部分岗位产生了冲击，我们需要提升自身能力以适应变革。',
    explanation: '前半句讨论"生活便利"，后半句突然跳到"取代工作"，偷换了讨论的核心概念。论证应保持概念的连贯性。',
    relatedLevel: 'L4-论证段专项',
    severity: 'high',
  },
  {
    id: 'cn-logic-2',
    subject: 'chinese',
    category: '逻辑类',
    subType: '以偏概全',
    errorExample: '我认识的几个大学生都找不到好工作，所以说现在的大学教育是失败的。',
    correctedExample: '部分大学生面临就业困难，这反映出高校人才培养与市场需求之间存在一定脱节。',
    explanation: '用少数个例推导整体结论，犯了以偏概全的逻辑错误。应使用更全面的数据或限定词来表述。',
    relatedLevel: 'L4-论证段专项',
    severity: 'high',
  },
  {
    id: 'cn-logic-3',
    subject: 'chinese',
    category: '逻辑类',
    subType: '因果倒置',
    errorExample: '因为经济发达了，所以人们更加重视教育，才使得这座城市经济发达。',
    correctedExample: '因为人们重视教育，培养了大量人才，所以这座城市经济得以快速发展。',
    explanation: '论证中把结果当成了原因，形成了循环论证。应理清因果链条，确保逻辑方向正确。',
    relatedLevel: 'L4-论证段专项',
    severity: 'medium',
  },
  {
    id: 'cn-logic-4',
    subject: 'chinese',
    category: '逻辑类',
    subType: '非黑即白',
    errorExample: '你要么支持创新，要么就是守旧派，没有第三种可能。',
    correctedExample: '在推进创新的过程中，我们既要勇于尝试新方法，也要善于汲取传统经验中的智慧。',
    explanation: '将复杂问题简单化为两个极端，忽略了中间地带和多元可能性。优秀的论证应展现思维的包容性。',
    relatedLevel: 'L4-论证段专项',
    severity: 'medium',
  },
  {
    id: 'cn-logic-5',
    subject: 'chinese',
    category: '逻辑类',
    subType: '滑坡谬误',
    errorExample: '如果允许学生使用手机，他们就会沉迷游戏，然后成绩下滑，最终毁掉前途。',
    correctedExample: '如果不对学生使用手机加以引导和规范，可能会影响他们的学习专注度。',
    explanation: '从一个合理前提推导出极端结论，中间缺乏必然的因果链。应避免过度推演。',
    relatedLevel: 'L4-论证段专项',
    severity: 'medium',
  },
]

const CHINESE_STRUCTURE_CASES: ErrorCase[] = [
  {
    id: 'cn-struct-1',
    subject: 'chinese',
    category: '结构类',
    subType: '缺乏论点',
    errorExample: '（全文讲述了袁隆平的故事，但没有明确提出论点）',
    correctedExample: '中心论点：坚持是成功的关键。以下用袁隆平的事例来论证这一观点。',
    explanation: '文章通篇只有事例叙述，缺少明确的中心论点统领全文，读者无法快速把握写作意图。',
    relatedLevel: 'L2-段落功能卡',
    severity: 'high',
  },
  {
    id: 'cn-struct-2',
    subject: 'chinese',
    category: '结构类',
    subType: '段落脱节',
    errorExample: '第一段讲诚信的重要性。第三段讲诚信是传统美德。两段之间没有任何过渡。',
    correctedExample: '第一段讲诚信的重要性。过渡段：这种重要性不仅体现在个人层面，更深深植根于中华传统文化之中。第三段讲诚信是传统美德。',
    explanation: '相邻段落之间缺少过渡衔接，导致文章读起来像拼凑的片段。应使用过渡句或过渡段来连接。',
    relatedLevel: 'L5-过渡段专项',
    severity: 'high',
  },
  {
    id: 'cn-struct-3',
    subject: 'chinese',
    category: '结构类',
    subType: '虎头蛇尾',
    errorExample: '开头引用名言、提出论点（200字）。论证段详细展开（300字）。结尾一句话收束（30字）。',
    correctedExample: '开头简明引论（100-150字）。论证段充分展开（400-500字）。结尾回扣论点并升华（100-150字）。',
    explanation: '开头过重而结尾草率，结构比例失衡。结尾应与开头呼应，起到总结升华的作用。',
    relatedLevel: 'L6-结尾段专项',
    severity: 'medium',
  },
  {
    id: 'cn-struct-4',
    subject: 'chinese',
    category: '结构类',
    subType: '开头离题',
    errorExample: '题目谈"坚持"，开头却花了大量篇幅描写四季更迭的自然美景。',
    correctedExample: '以四季更迭中蕴含的坚持之美引入，迅速点明"坚持"这一核心话题。',
    explanation: '开头铺垫过长，迟迟不切入主题，导致读者困惑。开头应简洁地引出论题。',
    relatedLevel: 'L3-开头段专项',
    severity: 'medium',
  },
  {
    id: 'cn-struct-5',
    subject: 'chinese',
    category: '结构类',
    subType: '论证单薄',
    errorExample: '论点：读书很重要。论据：读书很重要，因为书中有知识。所以我们要多读书。',
    correctedExample: '论点：读书很重要。论据1（事例）：鲁迅通过广泛阅读成为文学巨匠。论据2（道理）：高尔基说"书籍是人类进步的阶梯"。论据3（对比）：不读书的人视野受限。',
    explanation: '论证仅靠同义反复，缺乏多样化的论据支撑。应从不同角度、使用多种论证方法展开。',
    relatedLevel: 'L4-论证段专项',
    severity: 'high',
  },
]

const CHINESE_LANGUAGE_CASES: ErrorCase[] = [
  {
    id: 'cn-lang-1',
    subject: 'chinese',
    category: '语言类',
    subType: '口语化',
    errorExample: '这个事情真的很离谱，我觉得吧，这个人也太不靠谱了。',
    correctedExample: '这一事件令人深感遗憾，反映出部分人责任意识的缺失。',
    explanation: '文章语言过于口语化，缺乏书面语的规范性和文学性。议论文应使用严谨的书面表达。',
    relatedLevel: 'L7-全文整合',
    severity: 'medium',
  },
  {
    id: 'cn-lang-2',
    subject: 'chinese',
    category: '语言类',
    subType: '叙事过多',
    errorExample: '（议论文中用800字讲述了一个完整的故事，只有最后两句话是议论）',
    correctedExample: '用150字概述事例核心内容，再用300字展开分析论证。',
    explanation: '议论文中叙述篇幅远超议论，文体特征模糊。应以议论为主，叙述为辅。',
    relatedLevel: 'L4-论证段专项',
    severity: 'high',
  },
  {
    id: 'cn-lang-3',
    subject: 'chinese',
    category: '语言类',
    subType: '病句',
    errorExample: '通过这次活动，使我们认识到了团结的力量。',
    correctedExample: '这次活动使我们认识到了团结的力量。',
    explanation: '"通过……使……"连用导致句子缺少主语，属于常见的语法错误。',
    relatedLevel: 'L7-全文整合',
    severity: 'medium',
  },
  {
    id: 'cn-lang-4',
    subject: 'chinese',
    category: '语言类',
    subType: '用词不当',
    errorExample: '他的学习成绩一直很优秀，但是他的品德也很高尚。',
    correctedExample: '他的学习成绩一直很优秀，更难得的是他的品德也很高尚。',
    explanation: '"但是"表示转折，而前后两句是递进关系，应使用"更""而且"等递进连词。',
    relatedLevel: 'L7-全文整合',
    severity: 'low',
  },
  {
    id: 'cn-lang-5',
    subject: 'chinese',
    category: '语言类',
    subType: '重复啰嗦',
    errorExample: '他是一个非常非常优秀的人，他的优秀是大家有目共睹、众所周知的。',
    correctedExample: '他是一位广受认可的优秀人才。',
    explanation: '同一意思反复表达，造成语言冗余。应追求表达的精炼和准确。',
    relatedLevel: 'L7-全文整合',
    severity: 'low',
  },
]

const CHINESE_NORM_CASES: ErrorCase[] = [
  {
    id: 'cn-norm-1',
    subject: 'chinese',
    category: '规范类',
    subType: '标点误用',
    errorExample: '我们要学习什么呢？学习坚持，学习毅力，学习勇气。',
    correctedExample: '我们要学习什么？学习坚持，学习毅力，学习勇气。',
    explanation: '自问自答不需要问号，第一个问号应改为逗号。这属于标点符号使用规范。',
    relatedLevel: 'L7-全文整合',
    severity: 'low',
  },
  {
    id: 'cn-norm-2',
    subject: 'chinese',
    category: '规范类',
    subType: '错别字',
    errorExample: '我们应该克报困难，勇往直前。',
    correctedExample: '我们应该克服困难，勇往直前。',
    explanation: '"克报"应为"克服"，属于常见错别字。高考作文中错别字会扣分。',
    relatedLevel: 'L7-全文整合',
    severity: 'medium',
  },
  {
    id: 'cn-norm-3',
    subject: 'chinese',
    category: '规范类',
    subType: '卷面潦草',
    errorExample: '（字迹潦草、涂改过多、排版混乱的作文）',
    correctedExample: '（字迹工整、段落分明、标点规范的作文）',
    explanation: '卷面整洁是作文评分的重要因素。潦草的字迹会影响阅卷老师的第一印象。',
    relatedLevel: 'L7-全文整合',
    severity: 'medium',
  },
  {
    id: 'cn-norm-4',
    subject: 'chinese',
    category: '规范类',
    subType: '格式错误',
    errorExample: '（应用文缺少称呼、落款、日期等必要格式要素）',
    correctedExample: '（按照应用文格式规范：称呼居左顶格，正文空两格，落款右对齐，日期在落款下方）',
    explanation: '应用文有严格的格式要求，缺少必要要素会被扣分。应在写作前熟悉各类应用文格式。',
    relatedLevel: 'L3-开头段专项',
    severity: 'high',
  },
  {
    id: 'cn-norm-5',
    subject: 'chinese',
    category: '规范类',
    subType: '字数不足',
    errorExample: '（要求800字以上，实际只写了500字）',
    correctedExample: '（按照要求完成800字以上的完整作文）',
    explanation: '字数不足是高考作文的基本扣分项。应在构思时合理分配各段字数。',
    relatedLevel: 'L7-全文整合',
    severity: 'high',
  },
]

// ==================== English Error Cases ====================

const ENGLISH_GRAMMAR_CASES: ErrorCase[] = [
  {
    id: 'en-gram-1',
    subject: 'english',
    category: '语法类',
    subType: '主谓不一致',
    errorExample: 'The group of students were excited about the trip.',
    correctedExample: 'The group of students was excited about the trip.',
    explanation: '"The group" is a singular collective noun and requires a singular verb. The prepositional phrase "of students" does not affect subject-verb agreement.',
    relatedLevel: 'L5-语法纠错',
    severity: 'high',
  },
  {
    id: 'en-gram-2',
    subject: 'english',
    category: '语法类',
    subType: '时态错误',
    errorExample: 'Yesterday, I go to the store and buy some milk.',
    correctedExample: 'Yesterday, I went to the store and bought some milk.',
    explanation: 'When describing past events with a past time marker like "yesterday," all verbs should be in past tense.',
    relatedLevel: 'L5-语法纠错',
    severity: 'high',
  },
  {
    id: 'en-gram-3',
    subject: 'english',
    category: '语法类',
    subType: '冠词缺失',
    errorExample: 'She is honest person who always tells truth.',
    correctedExample: 'She is an honest person who always tells the truth.',
    explanation: 'The article "an" is needed before "honest" (vowel sound). "The truth" requires a definite article because it refers to a specific concept.',
    relatedLevel: 'L5-语法纠错',
    severity: 'medium',
  },
  {
    id: 'en-gram-4',
    subject: 'english',
    category: '语法类',
    subType: '介词错误',
    errorExample: 'I am interested on learning new languages.',
    correctedExample: 'I am interested in learning new languages.',
    explanation: 'The adjective "interested" always takes the preposition "in," not "on." Preposition搭配 must be memorized.',
    relatedLevel: 'L5-语法纠错',
    severity: 'medium',
  },
  {
    id: 'en-gram-5',
    subject: 'english',
    category: '语法类',
    subType: '动名词混淆',
    errorExample: 'I enjoy to read books before going to bed.',
    correctedExample: 'I enjoy reading books before going to bed.',
    explanation: 'The verb "enjoy" is followed by a gerund (V-ing), not an infinitive. Other verbs that take gerunds include: avoid, finish, mind, suggest.',
    relatedLevel: 'L5-语法纠错',
    severity: 'medium',
  },
]

const ENGLISH_SENTENCE_CASES: ErrorCase[] = [
  {
    id: 'en-sent-1',
    subject: 'english',
    category: '句式类',
    subType: '中式英语',
    errorExample: 'Although it is raining, but I still want to go out.',
    correctedExample: 'Although it is raining, I still want to go out.',
    explanation: '"Although" and "but" should not be used together. In Chinese, "虽然...但是..." is a common pair, but English only uses one conjunction.',
    relatedLevel: 'L1-句式仿写',
    severity: 'high',
  },
  {
    id: 'en-sent-2',
    subject: 'english',
    category: '句式类',
    subType: '句子碎片',
    errorExample: 'Because I was tired. I decided to go to sleep early.',
    correctedExample: 'Because I was tired, I decided to go to sleep early.',
    explanation: 'A dependent clause standing alone without an independent clause forms a sentence fragment. Combine it with the main clause.',
    relatedLevel: 'L2-段落骨架',
    severity: 'high',
  },
  {
    id: 'en-sent-3',
    subject: 'english',
    category: '句式类',
    subType: '句式单一',
    errorExample: 'I like reading. I like writing. I like singing. I like dancing.',
    correctedExample: 'I enjoy various activities, including reading, writing, singing, and dancing.',
    explanation: 'Repeating the same simple sentence structure makes writing monotonous. Use compound/complex sentences and varied structures.',
    relatedLevel: 'L1-句式仿写',
    severity: 'medium',
  },
  {
    id: 'en-sent-4',
    subject: 'english',
    category: '句式类',
    subType: '连词堆砌',
    errorExample: 'And moreover, besides that, in addition to this, also we should consider.',
    correctedExample: 'Furthermore, we should also consider other factors.',
    explanation: 'Using too many transitional words in succession makes the sentence unclear. Choose one appropriate connector.',
    relatedLevel: 'L2-段落骨架',
    severity: 'medium',
  },
  {
    id: 'en-sent-5',
    subject: 'english',
    category: '句式类',
    subType: '被动语态误用',
    errorExample: 'The book was read by me yesterday and it was enjoyed very much by me.',
    correctedExample: 'I read the book yesterday and enjoyed it very much.',
    explanation: 'Unnecessarily using passive voice makes sentences wordy. Active voice is preferred when the agent is known and important.',
    relatedLevel: 'L1-句式仿写',
    severity: 'medium',
  },
]

const ENGLISH_CONTENT_CASES: ErrorCase[] = [
  {
    id: 'en-content-1',
    subject: 'english',
    category: '内容类',
    subType: '偏题',
    errorExample: 'The prompt asks about the benefits of reading, but the essay discusses the history of books.',
    correctedExample: 'The essay directly addresses how reading benefits personal growth, knowledge acquisition, and mental health.',
    explanation: 'Going off-topic is one of the most common reasons for low scores. Always refer back to the prompt requirements.',
    relatedLevel: 'L6-全文写作',
    severity: 'high',
  },
  {
    id: 'en-content-2',
    subject: 'english',
    category: '内容类',
    subType: '论据不足',
    errorExample: 'Reading is good. We should all read more books. Books are important.',
    correctedExample: 'Reading enhances vocabulary by 20% on average (research data), and students who read daily score 15% higher on standardized tests.',
    explanation: 'Repeating the same idea without evidence or examples makes the argument weak. Support claims with specific details.',
    relatedLevel: 'L6-全文写作',
    severity: 'high',
  },
  {
    id: 'en-content-3',
    subject: 'english',
    category: '内容类',
    subType: '内容空洞',
    errorExample: 'The environment is very important. We need to protect it. Everyone should do their part.',
    correctedExample: 'Reducing plastic waste by using reusable bags can decrease ocean pollution by 30%, as evidenced by coastal cleanup data.',
    explanation: 'Vague statements without concrete details or data make writing feel empty. Be specific and provide examples.',
    relatedLevel: 'L6-全文写作',
    severity: 'medium',
  },
  {
    id: 'en-content-4',
    subject: 'english',
    category: '内容类',
    subType: '缺乏连贯',
    errorExample: 'Technology is advancing. Weather was nice yesterday. Education needs reform.',
    correctedExample: 'Technology is transforming education through online learning platforms, which have made knowledge more accessible than ever before.',
    explanation: 'Jumping between unrelated topics without logical connection makes the essay incoherent. Each sentence should flow from the previous one.',
    relatedLevel: 'L2-段落骨架',
    severity: 'high',
  },
  {
    id: 'en-content-5',
    subject: 'english',
    category: '内容类',
    subType: '观点矛盾',
    errorExample: 'Social media brings people together. However, social media isolates people from real life.',
    correctedExample: 'While social media helps maintain long-distance relationships, excessive use may reduce face-to-face interactions.',
    explanation: 'Contradicting your own point without acknowledging nuance weakens your argument. Present a balanced view instead.',
    relatedLevel: 'L6-全文写作',
    severity: 'medium',
  },
]

const ENGLISH_FORMAT_CASES: ErrorCase[] = [
  {
    id: 'en-format-1',
    subject: 'english',
    category: '格式类',
    subType: '段落缩进错误',
    errorExample: 'First paragraph indented. Second paragraph starts at the left margin without indentation.',
    correctedExample: 'All paragraphs should have consistent indentation (usually one tab or 4 spaces).',
    explanation: 'Inconsistent paragraph indentation looks unprofessional. Maintain uniform formatting throughout.',
    relatedLevel: 'L6-全文写作',
    severity: 'low',
  },
  {
    id: 'en-format-2',
    subject: 'english',
    category: '格式类',
    subType: '书信格式错误',
    errorExample: 'Dear Sir, How are you? I am writing to... Best wishes, Li Hua (no date, no address)',
    correctedExample: 'Include proper elements: Date, Salutation, Body paragraphs, Closing (Yours sincerely/faithfully), Signature.',
    explanation: 'Formal letters require specific structural elements. Missing any required element will lose format points.',
    relatedLevel: 'L3-应用文格式',
    severity: 'high',
  },
  {
    id: 'en-format-3',
    subject: 'english',
    category: '格式类',
    subType: '标点混用',
    errorExample: 'I like apples、bananas and oranges.',
    correctedExample: 'I like apples, bananas, and oranges.',
    explanation: 'Chinese punctuation marks (、) should not appear in English writing. Use the English comma (,) instead.',
    relatedLevel: 'L6-全文写作',
    severity: 'medium',
  },
  {
    id: 'en-format-4',
    subject: 'english',
    category: '格式类',
    subType: '大小写错误',
    errorExample: 'i think That Education is important. because it changes Our future.',
    correctedExample: 'I think that education is important because it changes our future.',
    explanation: 'Capitalize the first word of each sentence and the pronoun "I." Do not capitalize common nouns mid-sentence.',
    relatedLevel: 'L6-全文写作',
    severity: 'medium',
  },
  {
    id: 'en-format-5',
    subject: 'english',
    category: '格式类',
    subType: '续写格式问题',
    errorExample: '直接接着原文续写，没有分段，也没有衔接原文的最后一句。',
    correctedExample: '续写时注意：1) 与原文最后一句自然衔接 2) 合理分段 3) 保持原文的时态和人称一致',
    explanation: '读后续写需要与原文无缝衔接，同时保持独立的故事发展。格式上要注意分段和过渡。',
    relatedLevel: 'L4-读后续写开头',
    severity: 'high',
  },
]

export const ALL_ERROR_CASES: ErrorCase[] = [
  ...CHINESE_LOGIC_CASES,
  ...CHINESE_STRUCTURE_CASES,
  ...CHINESE_LANGUAGE_CASES,
  ...CHINESE_NORM_CASES,
  ...ENGLISH_GRAMMAR_CASES,
  ...ENGLISH_SENTENCE_CASES,
  ...ENGLISH_CONTENT_CASES,
  ...ENGLISH_FORMAT_CASES,
]

export function getErrorCases(
  subject?: 'chinese' | 'english',
  category?: string
): ErrorCase[] {
  return ALL_ERROR_CASES.filter(c => {
    if (subject && c.subject !== subject) return false
    if (category && c.category !== category) return false
    return true
  })
}
